In [ ]:
import pandas as pd
import numpy as np
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', 20)
from sklearn.model_selection import RandomizedSearchCV
import numpy as np
from scipy.stats import randint, uniform
import joblib
from sklearn.model_selection import cross_val_predict
import csv

### Data Preprocessing

In [424]:
df = pd.read_csv("./datasets/new_raw.csv")
first = ["name", "nvar"]
df = df[first + [c for c in df.columns if c not in first]]
df["nvar"].value_counts
df = df.sort_values(["name", "nvar", "mem"]).reset_index()
df

,index,name,nvar,nvmops,objective,eval_duration_solver,extract_duration_solver,stats_elapsed_time,dual_feas,status,timed_bytes,timed_time,timed_gctime,nlp_warmup_time,mem,neval_grad,iter,source_solver,problem,neval_obj,timestamp_solver,error_solver,vector_type,extract_duration_problem,highest_degree (ExprTree),nln_nnzj,adbackend_hessian_backend_type,minimize,count_plus_minus,alloc_obj,jtprod_available,has_equalities,time_hprod,adbackend_jprod_residual_backend_type,adbackend_ghjvprod_backend_type,nnln,jprod_residual_available,nlvb,nlvo,nlp_type,unconstrained,adbackend_jacobian_backend_type,adbackend_jprod_backend_type,hprod_residual_available,jac_available,hess_residual_available,adbackend_gradient_backend_type,float_type,ncon,is_nls,nnzo,nlvc,tree_length,count_trigonometric_function,matrix_free,nlin,time_obj,tree_depth,is_constant (ExprTree),nnzj,alloc_hprod,adbackend_jacobian_residual_backend_type,generator,alloc_hess,hess_available,count_exponential_function,islp,count_op_function,error_problem,adbackend_hprod_residual_backend_type,equality_constrained,time_grad,source_problem,has_bounds,grad_available,clinvals_nnz,jac_residual_available,bound_constrained,jprod_available,eval_duration_problem,adbackend_hessian_residual_backend_type,nequ,adbackend_jtprod_residual_backend_type,has_inequalities,is_linear (ExprTree),linearly_constrained,adbackend_jtprod_backend_type,hprod_available,jtprod_residual_available,alloc_grad,inequality_constrained,time_hess,lin_nnzj,nnzh,timestamp_problem,adbackend_hprod_backend_type,error_type,total_alloc
0,15939,arglina,100,1.0,5.000000e+01,0.319062,0.011306,0.000135,7.841650e-15,first_order,18576.0,0.000164,0.000000,0.377710,1,4.0,1.0,OptimizationProb...,OptimizationProb...,4.0,2026-02-28 18:33...,NaN,Vector{Float64},4.309682,2.0,0.0,ADNLPModels.Empt...,1.0,305.0,34515160.0,0.0,0.0,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100.0,100.0,ADNLPModel{Float...,1.0,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,0.0,NaN,ADNLPModels.Forw...,Float64,0.0,0.0,100.0,100.0,10404.0,0.0,1.0,0.0,0.376715,9.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,1.0,0.0,0.0,509.0,NaN,ADNLPModels.Empt...,0.0,0.464686,OptimizationProb...,0.0,1.0,0.0,NaN,0.0,0.0,1.980544,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,0.0,False,0.0,ADNLPModels.Empt...,1.0,NaN,4.261110e+07,0.0,NaN,0.0,5.050000e+03,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,7.712626e+07
1,15940,arglina,100,1.0,5.000000e+01,0.319062,0.011309,0.000151,7.841650e-15,first_order,22120.0,0.000199,0.000000,0.377710,2,2.0,1.0,OptimizationProb...,OptimizationProb...,2.0,2026-02-28 18:33...,NaN,Vector{Float64},4.309682,2.0,0.0,ADNLPModels.Empt...,1.0,305.0,34515160.0,0.0,0.0,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100.0,100.0,ADNLPModel{Float...,1.0,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,0.0,NaN,ADNLPModels.Forw...,Float64,0.0,0.0,100.0,100.0,10404.0,0.0,1.0,0.0,0.376715,9.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,1.0,0.0,0.0,509.0,NaN,ADNLPModels.Empt...,0.0,0.464686,OptimizationProb...,0.0,1.0,0.0,NaN,0.0,0.0,1.980544,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,0.0,False,0.0,ADNLPModels.Empt...,1.0,NaN,4.261110e+07,0.0,NaN,0.0,5.050000e+03,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,7.712626e+07
2,15941,arglina,100,1.0,5.000000e+01,0.319062,0.011275,0.000140,7.841650e-15,first_order,25592.0,0.000182,0.000000,0.377710,3,2.0,1.0,OptimizationProb...,OptimizationProb...,2.0,2026-02-28 18:33...,NaN,Vector{Float64},4.309682,2.0,0.0,ADNLPModels.Empt...,1.0,305.0,34515160.0,0.0,0.0,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100.0,100.0,ADNLPModel{Float...,1.0,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,0.0,NaN,ADNLPModels.Forw...,Float64,0.0,0.0,100.0,100.0,10404.0,0.0,1.0,0.0,0.376715,9.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,1.0,0.0,0.0,509.0,NaN,ADNLPModels.Empt...,0.0,0.464686,OptimizationProb...,0.0,1.0,0.0,NaN,0.0,0.0,1.980544,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,0.0,False,0.0,ADNLPModels.Empt...,1.0,NaN,4.261110e+07,0.0,NaN,0.0,5.050000e+03,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,7.712626e+07
3,15942,arglina,100,1.0,5.000000e+01,0.319062,0.011306,0.000151,7.841650e-15,first_order,29128.0,0.000195,0.000000,0.377710,4,2.0,1.0,OptimizationProb...,OptimizationProb...,2.0,2026-02-28 18:33...,NaN,Vector{Float64},4.309682,2.0,0.0,ADNLPModels.Empt...,1.0,305.0,34515160.0,0.0,0.0,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100.0,100.0,ADNLPModel{Float...,1.0,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,0.0,NaN,ADNLPModels.Forw...,Float64,0.0,0.0,100.0,100.0,10404.0,0.0,1.0,0.0,0.376715,9.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,1.0,0.0,0.0,509.0,NaN,ADNLPModels.Empt...,0.0,0.464686,OptimizationProb...,0.0,1.0,0.0,NaN,0.0,0.0,1.980544,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,0.0,False,0.0,ADNLPModels.Empt...,1.0,NaN,4.261110e+07,0.0,NaN,0.0,5.050000e+03,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,7.712626e+07
4,15943,arglina,100,1.0,5.000000e+01,0.319062,0.011287,0.000139,7.841650e-15,first_order,32600.0,0.000181,0.000000,0.377710,5,2.0,1.0,OptimizationProb...,OptimizationProb...,2.0,2026-02-28 18:33...,NaN,Vector{Float64},4.309682,2.0,0.0,ADNLPModels.Empt...,1.0,305.0,34515160.0,0.0,0.0,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100.0,100.0,ADNLPModel{Float...,1.0,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,0.0,NaN,ADNLPModels.Forw...,Float64,0.0,0.0,100.0,100.0,10404.0,0.0,1.0,0.0,0.376715,9.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,1.0,0.0,0.0,509.0,NaN,ADNLPModels.Empt...,0.0,0.464686,OptimizationProb...,0.0,1.0,0.0,NaN,0.0,0.0,1.980544,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,0.0,False,0.0,ADNLPModels.Empt...,1.0,NaN,4.261110e+07,0.0,NaN,0.0,5.050000e+03,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,7.712626e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21797,15198,woods,100000,49.0,5.685469e-09,0.805540,1280.073176,1279.820757,2.729926e-03,first_order,314448744.0,1280.072722,0.189891,59.331844,96,59.0,49.0,OptimizationProb...,OptimizationProb...,68.0,2026-03-09 15:12...,NaN,Vector{Float64},2813.283680,2.0,0.0,ADNLPModels.Empt...,True,275001.0,65309368.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,425000.0,0.0,True,0.0,0.073713,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,575001.0,NaN,ADNLPModels.Empt...,False,35.399378,OptimizationProb...,False,True,0.0,NaN,False,False,0.444649,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.573195e+10,False,NaN,0.0,5.000050e+09,2026-01-29 04:21...,ADNLPModels.Forw...,NaN,2.579726e+10
21798,15199,woods,100000,49.0,5.685469e-09,0.805540,1113.065603,1112.816634,2.729926e-03,first_order,317646328.0,1113.065141,0.190463,59.331844,97,59.0,49.0,OptimizationProb...,OptimizationProb...,68.0,2026-03-09 15:30...,NaN,Vector{Float64},2813.283680,2.0,0.0,ADNLPModels.Empt...,True,275001.0,65309368.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,425000.0,0.0,True,0.0,0.073713,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,575001.0,NaN,ADNLPModels.Empt...,False,35.399378,OptimizationProb...,False,True,0.0,NaN,False,False,0.444649,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.573195e+10,False,NaN,0.0,5.000050e+09,2026-01-29 04:21...,ADNLPModels.Forw...,NaN,2.579726e+10
21799,15200,woods,100000,49.0,5.685469e-09,0.805540,1162.403715,1162.156092,2.729926e-03,first_order,320848008.0,1162.403170,0.187345,59.331844,98,59.0,49.0,OptimizationProb...,OptimizationProb...,68.0,2026-03-09 15:49...,NaN,Vector{Float64},2813.283680,2.0,0.0,ADNLPModels.Empt...,True,275001.0,65309368.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,425000.0,0.0,True,0.0,0.073713,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,575001.0,NaN,ADNLPModels.Empt...,False,35.399378,OptimizationProb...,False,True,0.0,NaN,False,False,0.444649,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.573195e+10,False,NaN,0.0,5.000050e+09,2026-01-29 04:21...,ADNLPModels.Forw...,NaN,2.579726e+10
21800,15201,woods,100000,49.0,5.685469e-09,0.805540,1396.806612,1396.521273,2.729926e-03,first_order,324045592.0,1396.806032,0.215805,59.331844,99,59.0,49.0,OptimizationProb...,OptimizationProb...,68.0,2026-03-09 16:13...,NaN,Vector{Float64},2813.283680,2.0,0.0,ADNLPModels.Empt...,True,275001.0,65309368.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,425000.0,0.0,True,0.0,0.073713,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,575001.0,NaN,ADNLPModels.Empt...,False,35.399378,OptimizationProb...,False,True,0.0,NaN,False,False,0.444649,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.573195e+10,False,NaN,0.0,5.000050e+09,2026-01-29 04:21...,ADNLPModels.Forw...,NaN,2.579726e+10
21801,15202,woods,100000,49.0,5.685469e-09,0.805540,1328.463252,1328.197628,2.729926e-03,first_order,327247592.0,1328.462629,0.193347,59.331844,100,59.0,49.0,OptimizationProb...,OptimizationProb...,68.0,2026-03-09 16:35...,NaN,Vector{Float64},2813.283680,2.0,0.0,ADNLPModels.Empt...,True,275001.0,65309368.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,425000.0,0.0,True,0.0,0.073713,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,575001.0,NaN,ADNLPModels.Empt...,False,35.399378,OptimizationProb...,False,True,0.0,NaN,False,False,0.444649,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.573195e+10,False,NaN,0.0,5.000050e+09,2026-01-29 04:21...,ADNLPModels.Forw...,NaN,2.579726e+10

In [425]:
feature_cols_reg = [
                    # Core Features
                    "nvar", 
                    "mem",
                    "tree_length", 
                    "tree_depth", 
                    "time_obj",  # initial eval
                    "time_grad",
                    "extract_duration_problem",
                    
                    # Expression Tree Features
                    "highest_degree (ExprTree)",
                    "count_plus_minus",
                    "count_trigonometric_function",
                    "count_exponential_function",
                    "count_op_function",

                    # allocation
                    "alloc_obj",
                    "alloc_grad",
                    "total_alloc",
                  ]

target_cols_reg = [ "neval_obj",
                    "neval_grad",
                    "timed_bytes"] #(neval_obj, neval_grad, timed_bytes)

target_col_model = ["stats_elapsed_time"]

group_key = ["name", "nvar"]                                                                                                                   # [...]     
all_cols = list(set(feature_cols_reg + target_cols_reg + target_col_model + group_key))
solver_metrics = ['neval_grad', 'neval_obj', 'timed_bytes']
df[solver_metrics] = df[solver_metrics].fillna(0)
df = df[all_cols]
df.isna().sum().sort_values(ascending=False)

nvar                            0
extract_duration_problem        0
tree_depth                      0
tree_length                     0
stats_elapsed_time              0
highest_degree (ExprTree)       0
neval_grad                      0
timed_bytes                     0
time_obj                        0
count_op_function               0
name                            0
alloc_grad                      0
neval_obj                       0
mem                             0
count_plus_minus                0
count_trigonometric_function    0
time_grad                       0
total_alloc                     0
alloc_obj                       0
count_exponential_function      0
dtype: int64

In [426]:
df = df.copy()
df["mem_count"] = df.groupby(["name", "nvar"]).transform('size')
df = df[df["mem_count"] == 100].copy().reset_index(drop=True)
df

,nvar,extract_duration_problem,alloc_obj,total_alloc,time_grad,count_trigonometric_function,count_plus_minus,mem,neval_obj,alloc_grad,name,count_op_function,time_obj,timed_bytes,neval_grad,highest_degree (ExprTree),stats_elapsed_time,tree_length,tree_depth,count_exponential_function,mem_count
0,100,4.309682,34515160.0,7.712626e+07,0.464686,0.0,305.0,1,4.0,4.261110e+07,arglina,509.0,0.376715,18576.0,4.0,2.0,0.000135,10404.0,9.0,0.0,100
1,100,4.309682,34515160.0,7.712626e+07,0.464686,0.0,305.0,2,2.0,4.261110e+07,arglina,509.0,0.376715,22120.0,2.0,2.0,0.000151,10404.0,9.0,0.0,100
2,100,4.309682,34515160.0,7.712626e+07,0.464686,0.0,305.0,3,2.0,4.261110e+07,arglina,509.0,0.376715,25592.0,2.0,2.0,0.000140,10404.0,9.0,0.0,100
3,100,4.309682,34515160.0,7.712626e+07,0.464686,0.0,305.0,4,2.0,4.261110e+07,arglina,509.0,0.376715,29128.0,2.0,2.0,0.000151,10404.0,9.0,0.0,100
4,100,4.309682,34515160.0,7.712626e+07,0.464686,0.0,305.0,5,2.0,4.261110e+07,arglina,509.0,0.376715,32600.0,2.0,2.0,0.000139,10404.0,9.0,0.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21495,100000,2813.283680,65309368.0,2.579726e+10,35.399378,0.0,275001.0,96,68.0,2.573195e+10,woods,575001.0,0.073713,314448744.0,59.0,2.0,1279.820757,425000.0,7.0,0.0,100
21496,100000,2813.283680,65309368.0,2.579726e+10,35.399378,0.0,275001.0,97,68.0,2.573195e+10,woods,575001.0,0.073713,317646328.0,59.0,2.0,1112.816634,425000.0,7.0,0.0,100
21497,100000,2813.283680,65309368.0,2.579726e+10,35.399378,0.0,275001.0,98,68.0,2.573195e+10,woods,575001.0,0.073713,320848008.0,59.0,2.0,1162.156092,425000.0,7.0,0.0,100
21498,100000,2813.283680,65309368.0,2.579726e+10,35.399378,0.0,275001.0,99,68.0,2.573195e+10,woods,575001.0,0.073713,324045592.0,59.0,2.0,1396.521273,425000.0,7.0,0.0,100
21499,100000,2813.283680,65309368.0,2.579726e+10,35.399378,0.0,275001.0,100,68.0,2.573195e+10,woods,575001.0,0.073713,327247592.0,59.0,2.0,1328.197628,425000.0,7.0,0.0,100

In [427]:
# unique instances: one row per (problem, nvar)
instances = df[group_key].drop_duplicates()

# shuffle instances
instances = instances.sample(frac=1, random_state=66).reset_index(drop=True)

n = len(instances)
n_train = int(0.8 * n)

train_inst = instances.iloc[:n_train]
test_inst  = instances.iloc[n_train :]

# assign rows to splits by (problem, nvar)
train_df = df.merge(train_inst, on=["nvar", "name"], how="inner").reset_index(drop=True)
test_df  = df.merge(test_inst,  on=["nvar", "name"], how="inner").reset_index(drop=True)
all_df = pd.concat([train_df, test_df], axis=0)
all_df = all_df.reset_index(drop=True)
all_df

,nvar,extract_duration_problem,alloc_obj,total_alloc,time_grad,count_trigonometric_function,count_plus_minus,mem,neval_obj,alloc_grad,name,count_op_function,time_obj,timed_bytes,neval_grad,highest_degree (ExprTree),stats_elapsed_time,tree_length,tree_depth,count_exponential_function,mem_count
0,100,4.309682,34515160.0,77126264.0,0.464686,0.0,305.0,1,4.0,42611104.0,arglina,509.0,0.376715,18576.0,4.0,2.0,0.000135,10404.0,9.0,0.0,100
1,100,4.309682,34515160.0,77126264.0,0.464686,0.0,305.0,2,2.0,42611104.0,arglina,509.0,0.376715,22120.0,2.0,2.0,0.000151,10404.0,9.0,0.0,100
2,100,4.309682,34515160.0,77126264.0,0.464686,0.0,305.0,3,2.0,42611104.0,arglina,509.0,0.376715,25592.0,2.0,2.0,0.000140,10404.0,9.0,0.0,100
3,100,4.309682,34515160.0,77126264.0,0.464686,0.0,305.0,4,2.0,42611104.0,arglina,509.0,0.376715,29128.0,2.0,2.0,0.000151,10404.0,9.0,0.0,100
4,100,4.309682,34515160.0,77126264.0,0.464686,0.0,305.0,5,2.0,42611104.0,arglina,509.0,0.376715,32600.0,2.0,2.0,0.000139,10404.0,9.0,0.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21495,10000,74.643566,75185144.0,546412448.0,1.054803,0.0,27501.0,96,68.0,471227304.0,woods,57501.0,0.113105,31484720.0,59.0,2.0,7.757891,42500.0,7.0,0.0,100
21496,10000,74.643566,75185144.0,546412448.0,1.054803,0.0,27501.0,97,68.0,471227304.0,woods,57501.0,0.113105,31804864.0,59.0,2.0,7.755893,42500.0,7.0,0.0,100
21497,10000,74.643566,75185144.0,546412448.0,1.054803,0.0,27501.0,98,68.0,471227304.0,woods,57501.0,0.113105,32125008.0,59.0,2.0,7.753765,42500.0,7.0,0.0,100
21498,10000,74.643566,75185144.0,546412448.0,1.054803,0.0,27501.0,99,68.0,471227304.0,woods,57501.0,0.113105,32445152.0,59.0,2.0,7.755922,42500.0,7.0,0.0,100
21499,10000,74.643566,75185144.0,546412448.0,1.054803,0.0,27501.0,100,68.0,471227304.0,woods,57501.0,0.113105,32765616.0,59.0,2.0,7.759227,42500.0,7.0,0.0,100

In [428]:
 # confirm and use the three predicted feature to predict time                                                                                                              #  
X_train = train_df[feature_cols_reg].to_numpy(dtype=float)
X_test  = test_df[feature_cols_reg].to_numpy(dtype=float)

y_train = np.log1p(train_df[target_cols_reg].to_numpy(dtype=float))
y_test  = np.log1p(test_df[target_cols_reg].to_numpy(dtype=float))

X_all = np.concatenate([X_train, X_test], axis=0)

### Load Stage 1 RF and GB and form the Best Stage 1 Hybrid Model

In [429]:
rf_stage1 = joblib.load('./model_weights/best_rf_model_reg.pkl')
gb_stage1 = joblib.load('./model_weights/best_xgb_model_reg.pkl')

In [430]:
oof_train_rf = cross_val_predict(rf_stage1, X_train, y_train, cv=5, n_jobs=-1)
oof_train_gb = cross_val_predict(gb_stage1, X_train, y_train, cv=5, n_jobs=-1)

# Test set predictions are generated normally using the fully-fitted models
test_pred_rf = rf_stage1.predict(X_test)
test_pred_gb = gb_stage1.predict(X_test)

# Stack features in pure LOG-SPACE
X_train_time = np.column_stack([
    oof_train_rf[:, 0], 
    oof_train_rf[:, 1], 
    oof_train_gb[:, 2]
])

X_test_time = np.column_stack([
    test_pred_rf[:, 0], 
    test_pred_rf[:, 1], 
    test_pred_gb[:, 2]
])

In [431]:
y_train_time = np.log1p(train_df[target_col_model].to_numpy(dtype=float)).ravel()
y_test_time = np.log1p(test_df[target_col_model].to_numpy(dtype=float)).ravel()

### Performance Ratio Global Function

In [376]:
import numpy as np
import pandas as pd
from scipy.stats import gmean

def evaluate_model(model, label="Model"):
    """
    Evaluates a stage-2 model using global X_test_time and global test_df.
    Includes arithmetic mean, geometric mean, and maximum performance ratio metrics.
    """
    predictions = model.predict(X_test_time)
    working_df = test_df.copy() 
    
    working_df["predicted_time"] = predictions
    group_cols = ["name", "nvar"]

    # 1. Model Selection
    model_choices = (
        working_df.sort_values(by=group_cols + ["predicted_time", "mem"], ascending=[True, True, True, False])
        .groupby(group_cols).first().reset_index()
        [group_cols + ["mem", "predicted_time", "stats_elapsed_time"]]
        .rename(columns={"mem": "predicted_mem", "stats_elapsed_time": "actual_time"})
    )

    # 2. Oracle Selection
    oracle_choices = (
        working_df.sort_values(by=group_cols + ["stats_elapsed_time", "mem"], ascending=[True, True, True, False])
        .groupby(group_cols).first().reset_index()
        [group_cols + ["mem", "stats_elapsed_time"]]
        .rename(columns={"mem": "best_mem", "stats_elapsed_time": "best_time"})
    )

    # 3. Merge Matrix & Apply Hardened 0.10s Absolute Tolerance Filter
    final_df = pd.merge(model_choices, oracle_choices, on=group_cols).copy()
    final_df['actual_time'] = pd.to_numeric(final_df['actual_time'], errors='coerce')
    final_df['best_time'] = pd.to_numeric(final_df['best_time'], errors='coerce')

    final_df['raw_ratio'] = final_df['actual_time'] / final_df['best_time']
    time_diff = np.abs(final_df['actual_time'] - final_df['best_time'])
    final_df['performance_ratio'] = np.where(time_diff <= 0.10, 1.0, final_df['raw_ratio'])

    # Reorder display columns
    column_order = group_cols + ["predicted_mem", "predicted_time", "actual_time", "best_mem", "best_time", "performance_ratio", "raw_ratio"]
    final_df = final_df[column_order]

    # Output Summary Blocks
    print("\n" + "="*145)
    print(f"PER-PROBLEM PERFORMANCE PROFILE SUMMARY ({label.upper()})")
    print("="*145)
    print(final_df.to_string(index=False, formatters={
        'predicted_time': '{:.4f}'.format, 'actual_time': '{:.4f}'.format,
        'best_time': '{:.4f}'.format, 'performance_ratio': '{:.4f}'.format, 'raw_ratio': '{:.4f}'.format
    }))
    print("="*145)

    total_actual = final_df['actual_time'].sum()
    total_best = final_df['best_time'].sum()
    
    # Calculate Core Evaluation Statistics
    global_mean_ratio = final_df['performance_ratio'].mean()
    geom_mean_ratio = gmean(final_df['performance_ratio'])  # Clean Scipy implementation
    max_performance_ratio = final_df['performance_ratio'].max()
    
    print("\n" + "="*50)
    print(f"AGGREGATE METRICS ({label.upper()})")
    print("="*50)
    print(final_df['performance_ratio'].quantile([0.50, 0.75, 0.90]).to_string(float_format='{:.4f}'.format))
    print("-"*50)
    print(f"Global Mean Perf. Ratio     : {global_mean_ratio:.4f}")
    print(f"Geometric Mean Perf. Ratio  : {geom_mean_ratio:.4f}")
    print(f"Maximum Performance Ratio   : {max_performance_ratio:.4f}")
    print("-"*50)
    print(f"Total Actual Compute Time   : {total_actual:.4f}s")
    print(f"Total Oracle Optimal Time   : {total_best:.4f}s")
    print("="*50)
    
    return final_df

## Train Model directly on Best Stage 1 Hybrid Model Predicted Features

### Using Predicted Data from Best Stage 1 Hybrid Model For Linear Regression

In [432]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_predict
import joblib  # Standard library for saving scikit-learn models

In [396]:
# Initialize Stage 2 Linear Regression Regressor
lr_predictor = LinearRegression()

# 1. 5-Fold Cross-Validation Step (on Training Data in log-space)
cv_pred_log = cross_val_predict(lr_predictor, X_train_time, y_train_time, cv=5)
cv_mse = mean_squared_error(y_train_time, cv_pred_log)
cv_r2 = r2_score(y_train_time, cv_pred_log)

print("--- 5-Fold Cross-Validation Metrics (Train Set - Log Scale) ---")
print(f"CV MSE = {cv_mse:.4f} | CV R² = {cv_r2:.4f}")

# 2. Final Fit and Test Prediction
lr_predictor.fit(X_train_time, y_train_time)
pred_log = lr_predictor.predict(X_test_time)

# 3. Inverse-Transform to Original Physical Scale for Evaluation Metrics
# y_test_orig = np.expm1(y_test_time)
# pred_orig = np.expm1(pred_log)

test_mse = mean_squared_error(y_test_time, pred_log)
test_r2 = r2_score(y_test_time, pred_log)

print("\n--- Final Test Set Metrics (Original Physical Scale) ---")
print(f"MSE = {test_mse:.4f} | R² = {test_r2:.4f}")

# 4. Quantiled Relative Error Distribution (Original Scale)
relative_error = np.abs(pred_log - y_test_time) / (np.abs(y_test_time) + 1e-8)

quantiles = [0.25, 0.50, 0.75]
print("\n--- Quantiled Relative Error Q(q) (Test Set) ---")
print(f"{target_col_model}:")
print(f"Quantile (q) | Relative Error Value Q(q)")

q_values = np.quantile(relative_error, quantiles)
for q, val in zip(quantiles, q_values):
    print(f"  Q({q:.2f}):  {val:.4f}")

--- 5-Fold Cross-Validation Metrics (Train Set - Log Scale) ---
CV MSE = 2.1330 | CV R² = 0.6868

--- Final Test Set Metrics (Original Physical Scale) ---
MSE = 1.8783 | R² = 0.5841

--- Quantiled Relative Error Q(q) (Test Set) ---
['stats_elapsed_time']:
Quantile (q) | Relative Error Value Q(q)
  Q(0.25):  0.3517
  Q(0.50):  0.8962
  Q(0.75):  12.4978

In [397]:
evaluate_model(lr_predictor)

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (MODEL)
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100              1        -0.5404      0.0002         1    0.0002            1.0000    1.0000
     argtrig    100              1        -0.9216      0.0135        61    0.0081            1.0000    1.6555
     arwhead   1000              1         0.8167      0.0589         3    0.0401            1.0000    1.4710
     brownal    100              1        -0.5861      0.0003         1    0.0003            1.0000    1.0000
      brybnd  10000              3         3.2076     24.3856         1   23.0197            1.0593    1.0593
    clplatea    961              3         0.7494      4.1646        97    1.0576            3.9377    3.9377
    clplatec    100              1        -0.6780      0.9991        87    0.0129           77.6369   77.6369
      cosine    100              1        -0.9879      0.0006         1    0.0006            1.0000    1.0000
    cragglvy   1000              1         1.0034      0.4154        12    0.2475            1.6785    1.6785
    cragglvy  10000              3         2.5642     27.0828         6   24.4994            1.1054    1.1054
   cragglvy2   1000              2         0.8578      0.3639        27    0.2948            1.0000    1.2345
       curly    100              1        -0.9569      0.3982        96    0.0414            9.6253    9.6253
     curly30   1000              3        -0.0720    234.7077        99  124.8367            1.8801    1.8801
    dixmaanf   9999              3         3.0579    421.9444        56  305.1083            1.3829    1.3829
    dixmaang   9999              3         2.6710    304.6573        87  281.7172            1.0814    1.0814
    dixmaani     99              1        -0.8569      0.0719        96    0.0352            1.0000    2.0428
    dixmaank    999              1         0.8758      3.3225       100    2.9637            1.1210    1.1210
    dixmaanl    999              1         0.8511      3.0857        66    2.2922            1.3462    1.3462
    dixmaanl   9999              3         3.1693    314.1778        32  251.7549            1.2480    1.2480
    dixmaann     99              1        -0.7066      0.1408        99    0.0486            1.0000    2.8956
    dixmaann    999              1         0.7960     20.1127         1   20.1127            1.0000    1.0000
     dqdrtic   1000              1         0.8913      0.0895         9    0.0307            1.0000    2.9161
    extrosnb 100000              3         4.6303    915.9380        79  533.5132            1.7168    1.7168
fletcbv3_mod  10000              2         3.6244     49.9359         2   49.9359            1.0000    1.0000
    fletchcr   1000              2         0.3629      7.3626        36    4.0615            1.8128    1.8128
    freuroth    100              1        -0.2389      0.0044        23    0.0020            1.0000    2.1635
    genhumps    100              1        -0.9579      0.1389         9    0.0745            1.0000    1.8636
       ncb20    100              1        -0.3312     75.2056        99    0.0598         1257.5161 1257.5161
      ncb20b   1000              3         1.0910    120.9686        96   26.6734            4.5352    4.5352
      nondia    100              1        -0.9913      0.0004         3    0.0003            1.0000    1.2614
    penalty1  10000              1         2.0802      8.0439         2    8.0374            1.0000    1.0008
    penalty3   1000              3         0.5292      3.5593        15    2.0990            1.6958    1.6958
      quartc  10000              1         1.9904      4.2661         1    4.2661            1.0000    1.0000
     sinquad   1000              2         0.6379      1.6662        52    0.6837            2.4369    2.4369
    sparsine   1000              1         0.6272    146.9439        99   48.9996            2.9989    2.9989
    sparsqur   1000              1         0.7522      0.1015         7    0.0832            1.0000    1.2201
    srosenbr    100              1        -0.7694      0.0011         4    0.0007            1.0000    1.6547
    tquartic    100              1        -0.9533      0.1181         4    0.0004          312.2667  312.2667
    tquartic 100000              3         4.6641    885.7972        75  471.3734            1.8792    1.8792
      tridia   1000              2         0.4394      2.4046        70    1.0818            2.2228    2.2228
      vardim   1000              3         0.7603     31.1225         6   31.0967            1.0000    1.0008
       woods    100              1        -0.9505      0.0031         6    0.0012            1.0000    2.6393
       woods  10000              1         2.0955     31.9976        12    7.3593            4.3479    4.3479
=================================================================================================================================================

==================================================
AGGREGATE METRICS (MODEL)
==================================================
0.50   1.0814
0.75   1.8797
0.90   4.4977
--------------------------------------------------
Global Mean Perf. Ratio     : 39.9193
Geometric Mean Perf. Ratio  : 2.0695
Maximum Performance Ratio   : 1257.5161
--------------------------------------------------
Total Actual Compute Time   : 3645.7731s
Total Oracle Optimal Time   : 2227.5261s
==================================================

,name,nvar,predicted_mem,predicted_time,actual_time,best_mem,best_time,performance_ratio,raw_ratio
0,arglinb,100,1,-0.540376,0.000229,1,0.000229,1.000000,1.000000
1,argtrig,100,1,-0.921597,0.013453,61,0.008126,1.000000,1.655547
2,arwhead,1000,1,0.816713,0.058931,3,0.040062,1.000000,1.470991
3,brownal,100,1,-0.586143,0.000280,1,0.000280,1.000000,1.000000
4,brybnd,10000,3,3.207568,24.385600,1,23.019709,1.059336,1.059336
5,clplatea,961,3,0.749397,4.164609,97,1.057629,3.937685,3.937685
6,clplatec,100,1,-0.677958,0.999100,87,0.012869,77.636894,77.636894
7,cosine,100,1,-0.987855,0.000634,1,0.000634,1.000000,1.000000
8,cragglvy,1000,1,1.003427,0.415430,12,0.247496,1.678532,1.678532
9,cragglvy,10000,3,2.564184,27.082774,6,24.499405,1.105446,1.105446
10,cragglvy2,1000,2,0.857769,0.363899,27,0.294773,1.000000,1.234505
11,curly,100,1,-0.956902,0.398220,96,0.041372,9.625332,9.625332
12,curly30,1000,3,-0.072046,234.707685,99,124.836701,1.880118,1.880118
13,dixmaanf,9999,3,3.057856,421.944442,56,305.108326,1.382933,1.382933
14,dixmaang,9999,3,2.670976,304.657296,87,281.717223,1.081429,1.081429
15,dixmaani,99,1,-0.856874,0.071946,96,0.035220,1.000000,2.042762
16,dixmaank,999,1,0.875818,3.322480,100,2.963739,1.121043,1.121043
17,dixmaanl,999,1,0.851097,3.085742,66,2.292193,1.346196,1.346196
18,dixmaanl,9999,3,3.169263,314.177805,32,251.754948,1.247951,1.247951
19,dixmaann,99,1,-0.706567,0.140809,99,0.048629,1.000000,2.895570
20,dixmaann,999,1,0.796031,20.112668,1,20.112668,1.000000,1.000000
21,dqdrtic,1000,1,0.891309,0.089514,9,0.030697,1.000000,2.916063
22,extrosnb,100000,3,4.630254,915.937967,79,533.513211,1.716805,1.716805
23,fletcbv3_mod,10000,2,3.624421,49.935938,2,49.935938,1.000000,1.000000
24,fletchcr,1000,2,0.362870,7.362597,36,4.061515,1.812771,1.812771
25,freuroth,100,1,-0.238869,0.004435,23,0.002050,1.000000,2.163526
26,genhumps,100,1,-0.957914,0.138901,9,0.074535,1.000000,1.863570
27,ncb20,100,1,-0.331186,75.205646,99,0.059805,1257.516114,1257.516114
28,ncb20b,1000,3,1.090960,120.968567,96,26.673420,4.535173,4.535173
29,nondia,100,1,-0.991260,0.000390,3,0.000309,1.000000,1.261372
30,penalty1,10000,1,2.080221,8.043927,2,8.037379,1.000000,1.000815
31,penalty3,1000,3,0.529194,3.559341,15,2.098970,1.695756,1.695756
32,quartc,10000,1,1.990409,4.266108,1,4.266108,1.000000,1.000000
33,sinquad,1000,2,0.637935,1.666181,52,0.683725,2.436917,2.436917
34,sparsine,1000,1,0.627215,146.943887,99,48.999589,2.998880,2.998880
35,sparsqur,1000,1,0.752172,0.101515,7,0.083205,1.000000,1.220057
36,srosenbr,100,1,-0.769441,0.001140,4,0.000689,1.000000,1.654671
37,tquartic,100,1,-0.953272,0.118078,4,0.000378,312.266709,312.266709
38,tquartic,100000,3,4.664117,885.797218,75,471.373380,1.879184,1.879184
39,tridia,1000,2,0.439427,2.404632,70,1.081799,2.222809,2.222809
40,vardim,1000,3,0.760273,31.122461,6,31.096726,1.000000,1.000828
41,woods,100,1,-0.950511,0.003067,6,0.001162,1.000000,2.639311
42,woods,10000,1,2.095450,31.997559,12,7.359282,4.347919,4.347919

### Using Predicted Data from Best Stage 1 Hybrid Model For Random Forest

In [ ]:
# import numpy as np
# import pandas as pd
# from scipy.stats import randint, uniform
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.model_selection import RandomizedSearchCV

# # ==============================================================================
# # SEARCH SPACE CONFIGURATION
# # ==============================================================================
# param_distributions = {
#     'n_estimators': randint(100, 300),
#     'max_depth': [None, 10, 20, 30],
#     'min_samples_split': randint(2, 10),
#     'min_samples_leaf': randint(1, 5),
#     'max_features': [0.5, 0.7, 'sqrt'],
#     'bootstrap': [True],
#     'min_impurity_decrease': uniform(0, 0.001), 
#     'ccp_alpha': uniform(0, 0.001),             
#     'criterion': ['squared_error', 'friedman_mse']
# }

# rf_stage2 = RandomForestRegressor(random_state=42, n_jobs=1)

# # Set n_iter=1000 and verbose=3 to print real-time fold updates
# time_random_search = RandomizedSearchCV(
#     rf_stage2,
#     param_distributions=param_distributions,
#     n_iter=1000,
#     cv=5,
#     scoring='neg_mean_squared_error',
#     n_jobs=4,
#     random_state=42,
#     verbose=3,
#     return_train_score=True,
#     error_score='raise'
# )

# print("Starting 1,000-iteration Randomized Search Cross-Validation...")
# print(f"Total Fits to Execute: {1000 * 5} (1000 iterations x 5 folds)\n")

# # Fit Stage 2 on log features to predict your log targets
# time_random_search.fit(X_train_time, y_train_time)

# # ==============================================================================
# # PROGRESSION LANDSCAPE ANALYSIS (Print Data Along the Way)
# # ==============================================================================
# results_df = pd.DataFrame(time_random_search.cv_results_)
# results_df['actual_mse'] = -results_df['mean_test_score']

# print("\n" + "="*80)
# print("RANDOM SEARCH SEARCH-SPACE LANDSCAPE (MILESTONE INTERVALS)")
# print("="*80)
# print("Checking performance distribution across the 1,000 runs:")

# # Print structural metrics at regular intervals across the search trajectory
# intervals = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 999]
# milestone_cols = ['actual_mse', 'mean_fit_time', 'param_n_estimators', 
#                   'param_max_depth', 'param_min_samples_split', 'param_min_samples_leaf']

# sorted_by_run = results_df.copy() # Keep sequential run order intact for tracking
# print(sorted_by_run[milestone_cols].iloc[intervals].to_string(index=True))

# print("\n" + "="*80)
# print("BEST HYPERPARAMETERS FOUND")
# print("="*80)
# print(f"Best Parameters : {time_random_search.best_params_}")
# print(f"Best Log-MSE    : {-time_random_search.best_score_:.4f}")
# print("="*80)

# # Export full log profile for deep investigation
# results_df.to_csv('rf_stage2_1000runs_trajectory.csv', index=False)

Starting 1,000-iteration Randomized Search Cross-Validation...
Total Fits to Execute: 5000 (1000 iterations x 5 folds)

Fitting 5 folds for each of 1000 candidates, totalling 5000 fits
[CV 2/5] END bootstrap=True, ccp_alpha=0.0003745401188473625, criterion=squared_error, max_depth=20, max_features=sqrt, min_impurity_decrease=0.0007796910002727693, min_samples_leaf=1, min_samples_split=8, n_estimators=221;, score=(train=-0.171, test=-2.842) total time=   1.3s
[CV 3/5] END bootstrap=True, ccp_alpha=0.0003745401188473625, criterion=squared_error, max_depth=20, max_features=sqrt, min_impurity_decrease=0.0007796910002727693, min_samples_leaf=1, min_samples_split=8, n_estimators=221;, score=(train=-0.182, test=-2.531) total time=   1.3s
[CV 4/5] END bootstrap=True, ccp_alpha=0.0003745401188473625, criterion=squared_error, max_depth=20, max_features=sqrt, min_impurity_decrease=0.0007796910002727693, min_samples_leaf=1, min_samples_split=8, n_estimators=221;, score=(train=-0.201, test=-1.869) total time=   1.3s
[CV 1/5] END bootstrap=True, ccp_alpha=0.0003745401188473625, criterion=squared_error, max_depth=20, max_features=sqrt, min_impurity_decrease=0.0007796910002727693, min_samples_leaf=1, min_samples_split=8, n_estimators=221;, score=(train=-0.192, test=-2.128) total time=   1.3s
[CV 5/5] END bootstrap=True, ccp_alpha=0.0003745401188473625, criterion=squared_error, max_depth=20, max_features=sqrt, min_impurity_decrease=0.0007796910002727693, min_samples_leaf=1, min_samples_split=8, n_estimators=221;, score=(train=-0.179, test=-4.330) total time=   1.2s
[CV 1/5] END bootstrap=True, ccp_alpha=0.00015599452033620266, criterion=squared_error, max_depth=20, max_features=0.5, min_impurity_decrease=0.0006011150117432088, min_samples_leaf=4, min_samples_split=4, n_estimators=249;, score=(train=-0.211, test=-2.051) total time=   1.4s
[CV 3/5] END bootstrap=True, ccp_alpha=0.00015599452033620266, criterion=squared_error, max_depth=20, max_features=0.5, min_impurity_decrease=0.0006011150117432088, min_samples_leaf=4, min_samples_split=4, n_estimators=249;, score=(train=-0.196, test=-2.474) total time=   1.4s
[CV 2/5] END bootstrap=True, ccp_alpha=0.00015599452033620266, criterion=squared_error, max_depth=20, max_features=0.5, min_impurity_decrease=0.0006011150117432088, min_samples_leaf=4, min_samples_split=4, n_estimators=249;, score=(train=-0.188, test=-2.865) total time=   1.4s
[CV 4/5] END bootstrap=True, ccp_alpha=0.00015599452033620266, criterion=squared_error, max_depth=20, max_features=0.5, min_impurity_decrease=0.0006011150117432088, min_samples_leaf=4, min_samples_split=4, n_estimators=249;, score=(train=-0.216, test=-1.795) total time=   1.4s
[CV 5/5] END bootstrap=True, ccp_alpha=0.00015599452033620266, criterion=squared_error, max_depth=20, max_features=0.5, min_impurity_decrease=0.0006011150117432088, min_samples_leaf=4, min_samples_split=4, n_estimators=249;, score=(train=-0.189, test=-4.143) total time=   1.4s
[CV 2/5] END bootstrap=True, ccp_alpha=5.641157902710026e-05, criterion=friedman_mse, max_depth=30, max_features=0.7, min_impurity_decrease=0.00021233911067827617, min_samples_leaf=4, min_samples_split=5, n_estimators=120;, score=(train=-0.094, test=-2.550) total time=   1.7s
[CV 1/5] END bootstrap=True, ccp_alpha=5.641157902710026e-05, criterion=friedman_mse, max_depth=30, max_features=0.7, min_impurity_decrease=0.00021233911067827617, min_samples_leaf=4, min_samples_split=5, n_estimators=120;, score=(train=-0.115, test=-2.722) total time=   1.7s
[CV 1/5] END bootstrap=True, ccp_alpha=0.0006174815096277166, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0004319450186421158, min_samples_leaf=1, min_samples_split=4, n_estimators=158;, score=(train=-0.343, test=-2.091) total time=   1.1s
[CV 3/5] END bootstrap=True, ccp_alpha=5.641157902710026e-05, criterion=friedman_mse, max_depth=30, max_features=0.7, min_impurity_decrease=0.00021233911067827617, min_samples_leaf=4, min_samples_split=5, n_estimators=120;, score=(train=-0.099, test=-2.944) total time=   1.8s
[CV 4/5] END bootstrap=True, ccp_alpha=5.641157902710026e-05, criterion=friedman_mse, max_depth=30, max_features=0.7, min_impurity_decrease=0.00021233911067827617, min_samples_leaf=4, min_samples_split=5, n_estimators=120;, score=(train=-0.114, test=-2.140) total time=   1.9s
[CV 5/5] END bootstrap=True, ccp_alpha=5.641157902710026e-05, criterion=friedman_mse, max_depth=30, max_features=0.7, min_impurity_decrease=0.00021233911067827617, min_samples_leaf=4, min_samples_split=5, n_estimators=120;, score=(train=-0.097, test=-4.995) total time=   1.8s
[CV 2/5] END bootstrap=True, ccp_alpha=0.0006174815096277166, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0004319450186421158, min_samples_leaf=1, min_samples_split=4, n_estimators=158;, score=(train=-0.303, test=-2.870) total time=   1.0s
[CV 3/5] END bootstrap=True, ccp_alpha=0.0006174815096277166, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0004319450186421158, min_samples_leaf=1, min_samples_split=4, n_estimators=158;, score=(train=-0.310, test=-2.144) total time=   1.0s
[CV 4/5] END bootstrap=True, ccp_alpha=0.0006174815096277166, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0004319450186421158, min_samples_leaf=1, min_samples_split=4, n_estimators=158;, score=(train=-0.359, test=-1.731) total time=   1.0s
[CV 5/5] END bootstrap=True, ccp_alpha=0.0006174815096277166, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0004319450186421158, min_samples_leaf=1, min_samples_split=4, n_estimators=158;, score=(train=-0.279, test=-4.411) total time=   1.0s
[CV 1/5] END bootstrap=True, ccp_alpha=0.0003998609717152555, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0004560699842170359, min_samples_leaf=3, min_samples_split=7, n_estimators=150;, score=(train=-0.136, test=-2.371) total time=   1.3s
[CV 2/5] END bootstrap=True, ccp_alpha=0.0003998609717152555, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0004560699842170359, min_samples_leaf=3, min_samples_split=7, n_estimators=150;, score=(train=-0.119, test=-2.793) total time=   1.3s
[CV 3/5] END bootstrap=True, ccp_alpha=0.0003998609717152555, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0004560699842170359, min_samples_leaf=3, min_samples_split=7, n_estimators=150;, score=(train=-0.128, test=-2.606) total time=   1.3s
[CV 4/5] END bootstrap=True, ccp_alpha=0.0003998609717152555, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0004560699842170359, min_samples_leaf=3, min_samples_split=7, n_estimators=150;, score=(train=-0.139, test=-1.915) total time=   1.3s
[CV 1/5] END bootstrap=True, ccp_alpha=0.00038246199126716276, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=4.645041271999773e-05, min_samples_leaf=3, min_samples_split=8, n_estimators=120;, score=(train=-0.140, test=-2.366) total time=   1.1s
[CV 5/5] END bootstrap=True, ccp_alpha=0.0003998609717152555, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0004560699842170359, min_samples_leaf=3, min_samples_split=7, n_estimators=150;, score=(train=-0.122, test=-4.246) total time=   1.3s
[CV 2/5] END bootstrap=True, ccp_alpha=0.00038246199126716276, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=4.645041271999773e-05, min_samples_leaf=3, min_samples_split=8, n_estimators=120;, score=(train=-0.120, test=-2.654) total time=   1.1s
[CV 3/5] END bootstrap=True, ccp_alpha=0.00038246199126716276, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=4.645041271999773e-05, min_samples_leaf=3, min_samples_split=8, n_estimators=120;, score=(train=-0.130, test=-2.577) total time=   1.1s
[CV 5/5] END bootstrap=True, ccp_alpha=0.00038246199126716276, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=4.645041271999773e-05, min_samples_leaf=3, min_samples_split=8, n_estimators=120;, score=(train=-0.123, test=-4.326) total time=   1.1s
[CV 4/5] END bootstrap=True, ccp_alpha=0.00038246199126716276, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=4.645041271999773e-05, min_samples_leaf=3, min_samples_split=8, n_estimators=120;, score=(train=-0.142, test=-1.867) total time=   1.1s
[CV 1/5] END bootstrap=True, ccp_alpha=0.000450499251969543, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=0.0009656320330745594, min_samples_leaf=2, min_samples_split=3, n_estimators=108;, score=(train=-0.112, test=-2.393) total time=   1.1s
[CV 2/5] END bootstrap=True, ccp_alpha=0.000450499251969543, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=0.0009656320330745594, min_samples_leaf=2, min_samples_split=3, n_estimators=108;, score=(train=-0.095, test=-2.729) total time=   1.1s
[CV 3/5] END bootstrap=True, ccp_alpha=0.000450499251969543, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=0.0009656320330745594, min_samples_leaf=2, min_samples_split=3, n_estimators=108;, score=(train=-0.108, test=-2.650) total time=   1.1s
[CV 4/5] END bootstrap=True, ccp_alpha=0.000450499251969543, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=0.0009656320330745594, min_samples_leaf=2, min_samples_split=3, n_estimators=108;, score=(train=-0.115, test=-1.910) total time=   1.1s
[CV 5/5] END bootstrap=True, ccp_alpha=0.000450499251969543, criterion=friedman_mse, max_depth=30, max_features=0.5, min_impurity_decrease=0.0009656320330745594, min_samples_leaf=2, min_samples_split=3, n_estimators=108;, score=(train=-0.103, test=-4.406) total time=   1.0s
[CV 1/5] END bootstrap=True, ccp_alpha=1.5966252220214196e-05, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0006832635188254582, min_samples_leaf=4, min_samples_split=6, n_estimators=107;, score=(train=-0.139, test=-2.195) total time=   0.8s
[CV 3/5] END bootstrap=True, ccp_alpha=1.5966252220214196e-05, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0006832635188254582, min_samples_leaf=4, min_samples_split=6, n_estimators=107;, score=(train=-0.124, test=-2.627) total time=   0.8s
[CV 2/5] END bootstrap=True, ccp_alpha=1.5966252220214196e-05, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0006832635188254582, min_samples_leaf=4, min_samples_split=6, n_estimators=107;, score=(train=-0.119, test=-2.666) total time=   0.9s
[CV 5/5] END bootstrap=True, ccp_alpha=1.5966252220214196e-05, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0006832635188254582, min_samples_leaf=4, min_samples_split=6, n_estimators=107;, score=(train=-0.115, test=-4.445) total time=   0.8s
[CV 4/5] END bootstrap=True, ccp_alpha=1.5966252220214196e-05, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0006832635188254582, min_samples_leaf=4, min_samples_split=6, n_estimators=107;, score=(train=-0.140, test=-1.895) total time=   0.9s
[CV 2/5] END bootstrap=True, ccp_alpha=3.43885211152184e-05, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.000662522284353982, min_samples_leaf=2, min_samples_split=7, n_estimators=233;, score=(train=-0.058, test=-2.537) total time=   3.3s
[CV 1/5] END bootstrap=True, ccp_alpha=3.43885211152184e-05, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.000662522284353982, min_samples_leaf=2, min_samples_split=7, n_estimators=233;, score=(train=-0.076, test=-2.739) total time=   3.4s
[CV 3/5] END bootstrap=True, ccp_alpha=3.43885211152184e-05, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.000662522284353982, min_samples_leaf=2, min_samples_split=7, n_estimators=233;, score=(train=-0.070, test=-3.022) total time=   3.3s
[CV 4/5] END bootstrap=True, ccp_alpha=3.43885211152184e-05, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.000662522284353982, min_samples_leaf=2, min_samples_split=7, n_estimators=233;, score=(train=-0.077, test=-2.244) total time=   3.3s
[CV 1/5] END bootstrap=True, ccp_alpha=0.00020794166286818884, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0009695846277645585, min_samples_leaf=2, min_samples_split=5, n_estimators=261;, score=(train=-0.340, test=-2.007) total time=   1.6s
[CV 2/5] END bootstrap=True, ccp_alpha=0.00020794166286818884, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0009695846277645585, min_samples_leaf=2, min_samples_split=5, n_estimators=261;, score=(train=-0.298, test=-2.798) total time=   1.6s
[CV 3/5] END bootstrap=True, ccp_alpha=0.00020794166286818884, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0009695846277645585, min_samples_leaf=2, min_samples_split=5, n_estimators=261;, score=(train=-0.310, test=-2.181) total time=   1.6s
[CV 5/5] END bootstrap=True, ccp_alpha=3.43885211152184e-05, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.000662522284353982, min_samples_leaf=2, min_samples_split=7, n_estimators=233;, score=(train=-0.066, test=-5.401) total time=   3.3s
[CV 4/5] END bootstrap=True, ccp_alpha=0.00020794166286818884, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0009695846277645585, min_samples_leaf=2, min_samples_split=5, n_estimators=261;, score=(train=-0.369, test=-1.727) total time=   1.6s
[CV 5/5] END bootstrap=True, ccp_alpha=0.00020794166286818884, criterion=friedman_mse, max_depth=10, max_features=0.5, min_impurity_decrease=0.0009695846277645585, min_samples_leaf=2, min_samples_split=5, n_estimators=261;, score=(train=-0.268, test=-4.308) total time=   1.6s
[CV 1/5] END bootstrap=True, ccp_alpha=0.00039515023600181443, criterion=friedman_mse, max_depth=10, max_features=sqrt, min_impurity_decrease=0.0009218742350231169, min_samples_leaf=4, min_samples_split=7, n_estimators=289;, score=(train=-0.363, test=-1.975) total time=   1.8s
[CV 3/5] END bootstrap=True, ccp_alpha=0.00039515023600181443, criterion=friedman_mse, max_depth=10, max_features=sqrt, min_impurity_decrease=0.0009218742350231169, min_samples_leaf=4, min_samples_split=7, n_estimators=289;, score=(train=-0.323, test=-2.221) total time=   1.7s
[CV 2/5] END bootstrap=True, ccp_alpha=0.00039515023600181443, criterion=friedman_mse, max_depth=10, max_features=sqrt, min_impurity_decrease=0.0009218742350231169, min_samples_leaf=4, min_samples_split=7, n_estimators=289;, score=(train=-0.330, test=-2.889) total time=   1.8s
[CV 4/5] END bootstrap=True, ccp_alpha=0.00039515023600181443, criterion=friedman_mse, max_depth=10, max_features=sqrt, min_impurity_decrease=0.0009218742350231169, min_samples_leaf=4, min_samples_split=7, n_estimators=289;, score=(train=-0.389, test=-1.678) total time=   1.8s
[CV 5/5] END bootstrap=True, ccp_alpha=0.00039515023600181443, criterion=friedman_mse, max_depth=10, max_features=sqrt, min_impurity_decrease=0.0009218742350231169, min_samples_leaf=4, min_samples_split=7, n_estimators=289;, score=(train=-0.292, test=-4.268) total time=   1.7s
[CV 2/5] END bootstrap=True, ccp_alpha=0.00032533033076326436, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.0005396921323890798, min_samples_leaf=4, min_samples_split=3, n_estimators=287;, score=(train=-0.107, test=-2.608) total time=   3.9s
[CV 1/5] END bootstrap=True, ccp_alpha=0.00032533033076326436, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.0005396921323890798, min_samples_leaf=4, min_samples_split=3, n_estimators=287;, score=(train=-0.128, test=-2.738) total time=   4.0s
[CV 3/5] END bootstrap=True, ccp_alpha=0.00032533033076326436, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.0005396921323890798, min_samples_leaf=4, min_samples_split=3, n_estimators=287;, score=(train=-0.113, test=-2.968) total time=   3.9s
[CV 4/5] END bootstrap=True, ccp_alpha=0.00032533033076326436, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.0005396921323890798, min_samples_leaf=4, min_samples_split=3, n_estimators=287;, score=(train=-0.127, test=-2.109) total time=   4.0s
[CV 1/5] END bootstrap=True, ccp_alpha=0.0005426960831582485, criterion=squared_error, max_depth=None, max_features=sqrt, min_impurity_decrease=0.0001652669390630025, min_samples_leaf=1, min_samples_split=8, n_estimators=108;, score=(train=-0.119, test=-2.309) total time=   0.7s
[CV 2/5] END bootstrap=True, ccp_alpha=0.0005426960831582485, criterion=squared_error, max_depth=None, max_features=sqrt, min_impurity_decrease=0.0001652669390630025, min_samples_leaf=1, min_samples_split=8, n_estimators=108;, score=(train=-0.103, test=-2.796) total time=   0.7s
[CV 3/5] END bootstrap=True, ccp_alpha=0.0005426960831582485, criterion=squared_error, max_depth=None, max_features=sqrt, min_impurity_decrease=0.0001652669390630025, min_samples_leaf=1, min_samples_split=8, n_estimators=108;, score=(train=-0.120, test=-2.618) total time=   0.7s
[CV 4/5] END bootstrap=True, ccp_alpha=0.0005426960831582485, criterion=squared_error, max_depth=None, max_features=sqrt, min_impurity_decrease=0.0001652669390630025, min_samples_leaf=1, min_samples_split=8, n_estimators=108;, score=(train=-0.125, test=-1.964) total time=   0.7s
[CV 5/5] END bootstrap=True, ccp_alpha=0.0005426960831582485, criterion=squared_error, max_depth=None, max_features=sqrt, min_impurity_decrease=0.0001652669390630025, min_samples_leaf=1, min_samples_split=8, n_estimators=108;, score=(train=-0.111, test=-4.374) total time=   0.7s
[CV 1/5] END bootstrap=True, ccp_alpha=0.0007722447692966575, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0008154614284548342, min_samples_leaf=1, min_samples_split=9, n_estimators=262;, score=(train=-0.132, test=-2.435) total time=   2.3s
[CV 2/5] END bootstrap=True, ccp_alpha=0.0007722447692966575, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0008154614284548342, min_samples_leaf=1, min_samples_split=9, n_estimators=262;, score=(train=-0.113, test=-2.796) total time=   2.4s
[CV 3/5] END bootstrap=True, ccp_alpha=0.0007722447692966575, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0008154614284548342, min_samples_leaf=1, min_samples_split=9, n_estimators=262;, score=(train=-0.131, test=-2.577) total time=   2.4s
[CV 5/5] END bootstrap=True, ccp_alpha=0.00032533033076326436, criterion=friedman_mse, max_depth=None, max_features=0.7, min_impurity_decrease=0.0005396921323890798, min_samples_leaf=4, min_samples_split=3, n_estimators=287;, score=(train=-0.111, test=-4.939) total time=   4.0s
[CV 4/5] END bootstrap=True, ccp_alpha=0.0007722447692966575, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0008154614284548342, min_samples_leaf=1, min_samples_split=9, n_estimators=262;, score=(train=-0.137, test=-1.910) total time=   2.4s
[CV 5/5] END bootstrap=True, ccp_alpha=0.0007722447692966575, criterion=friedman_mse, max_depth=30, max_features=sqrt, min_impurity_decrease=0.0008154614284548342, min_samples_leaf=1, min_samples_split=9, n_estimators=262;, score=(train=-0.124, test=-4.402) total time=   2.3s
[CV 1/5] END bootstrap=True, ccp_alpha=0.0007901755405312057, criterion=squared_error, max_depth=None, max_features=0.7, min_impurity_decrease=0.00035846572854427263, min_samples_leaf=1, min_samples_split=5, n_estimators=234;, score=(train=-0.112, test=-2.744) total time=   2.3s

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

================================================================================
RANDOM SEARCH SEARCH-SPACE LANDSCAPE (MILESTONE INTERVALS)
================================================================================
Checking performance distribution across the 1,000 runs:
     actual_mse  mean_fit_time  param_n_estimators param_max_depth  param_min_samples_split  param_min_samples_leaf
0      2.739877       1.234382                 221              20                        8                       1
100    3.232085       1.662720                 103            None                        6                       1
200    2.618096       1.413217                 257              10                        9                       2
300    3.149204       1.447265                 141              20                        7                       2
400    2.539607       1.113225                 218              10                        6                       3
500    3.136640       3.013652                 202            None                        9                       2
600    2.660830       1.661373                 295              20                        4                       3
700    2.620995       1.251822                 203              10                        7                       3
800    2.759531       1.856254                 221              30                        7                       3
900    2.743672       1.635814                 274            None                        4                       1
999    2.620429       0.870614                 157              10                        6                       1

================================================================================
BEST HYPERPARAMETERS FOUND
================================================================================
Best Parameters : {'bootstrap': True, 'ccp_alpha': 0.0005322575311489761, 'criterion': 'squared_error', 'max_depth': 10, 'max_features': 0.5, 'min_impurity_decrease': 0.0008336499619375856, 'min_samples_leaf': 3, 'min_samples_split': 4, 'n_estimators': 141}
Best Log-MSE    : 2.5275
================================================================================

In [398]:
time_best_model_rf = joblib.load('./model_weights/best_hybrid_rf_model_time_new_cv.pkl')
# time_best_model_rf = time_random_search.best_estimator_
accuracy = time_best_model_rf.score(X_test_time, y_test_time)
print(f"Time prediction accuracy based on predicted values={accuracy}")
# joblib.dump(time_best_model_rf, './model_weights/best_hybrid_rf_model_time_new_cv.pkl')
# joblib.dump(time_best_model_rf, './model_weights/best_hybrid_rf_model_time.pkl')

Time prediction accuracy based on predicted values=0.6236072929946244

In [399]:
pred = time_best_model_rf.predict(X_test_time)
test_mse = mean_squared_error(y_test_time, pred)
test_r2  = r2_score(y_test_time, pred)
print(f"MSE={test_mse:.4f}  R²={test_r2:.4f}")

# Compute pointwise relative error matching the paper's formula: |y - y_hat| / (|y| + delta)
relative_error = np.abs(pred - y_test_time) / (np.abs(y_test_time) + 1e-8)

# Quantiled Relative Error Distribution
quantiles = [0.25, 0.50, 0.75]
print("\n--- Quantiled Relative Error Q(q) (Test Set) ---")
for i, col in enumerate(target_col_model):
    print(f"\n{col}:")
    print(f"Quantile (q) | Relative Error Value Q(q)")
    
    # Safe extraction whether relative_error is a 1D vector or a 2D column matrix
    error_data = relative_error[:, i] if relative_error.ndim > 1 else relative_error
    q_values = np.quantile(error_data, quantiles)
    
    for q, val in zip(quantiles, q_values):
        print(f"  Q({q:.2f}):  {val:.4f}")
print(list(pred))

MSE=1.6999  R²=0.6236

--- Quantiled Relative Error Q(q) (Test Set) ---

stats_elapsed_time:
Quantile (q) | Relative Error Value Q(q)
  Q(0.25):  0.3084
  Q(0.50):  0.7746
  Q(0.75):  6.2418

In [400]:
evaluate_model(joblib.load('./model_weights/best_hybrid_rf_model_time_new_cv.pkl'))
# evaluate_model(joblib.load('./model_weights/best_hybrid_rf_model_time.pkl'))

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (MODEL)
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100              3         0.0637      0.0003         1    0.0002            1.0000    1.2844
     argtrig    100             50         0.0469      0.0100        61    0.0081            1.0000    1.2303
     arwhead   1000             47         0.3842      0.0461         3    0.0401            1.0000    1.1508
     brownal    100              7         0.0993      0.0003         1    0.0003            1.0000    1.0928
      brybnd  10000             20         2.1251     24.3788         1   23.0197            1.0590    1.0590
    clplatea    961              8         0.4257      2.1627        97    1.0576            2.0449    2.0449
    clplatec    100            100         0.0755      0.0208        87    0.0129            1.0000    1.6133
      cosine    100             29         0.0880      0.0010         1    0.0006            1.0000    1.6059
    cragglvy   1000             51         0.2998      0.3287        12    0.2475            1.0000    1.3282
    cragglvy  10000              1         3.6430     31.8165         6   24.4994            1.2987    1.2987
   cragglvy2   1000             44         0.7284      0.3175        27    0.2948            1.0000    1.0770
       curly    100             20         0.1536      0.1628        96    0.0414            3.9349    3.9349
     curly30   1000              2         0.5008    260.3860        99  124.8367            2.0858    2.0858
    dixmaanf   9999             10         3.6210    326.7383        56  305.1083            1.0709    1.0709
    dixmaang   9999              2         3.1796    341.0960        87  281.7172            1.2108    1.2108
    dixmaani     99             31         0.0504      0.0392        96    0.0352            1.0000    1.1133
    dixmaank    999             75         0.7784      3.1486       100    2.9637            1.0624    1.0624
    dixmaanl    999              3         0.4671      2.3740        66    2.2922            1.0000    1.0357
    dixmaanl   9999              3         3.7987    314.1778        32  251.7549            1.2480    1.2480
    dixmaann     99              3         0.0614      0.1369        99    0.0486            1.0000    2.8155
    dixmaann    999              2         0.3816     32.2710         1   20.1127            1.6045    1.6045
     dqdrtic   1000              1         0.6080      0.0895         9    0.0307            1.0000    2.9161
    extrosnb 100000              1         6.6820    981.8994        79  533.5132            1.8404    1.8404
fletcbv3_mod  10000             17         3.7193     81.0716         2   49.9359            1.6235    1.6235
    fletchcr   1000              3         0.3007      5.6988        36    4.0615            1.4031    1.4031
    freuroth    100              2         0.0470      0.0026        23    0.0020            1.0000    1.2859
    genhumps    100              3         0.0898      0.1065         9    0.0745            1.0000    1.4282
       ncb20    100              3         0.2684      0.3980        99    0.0598            6.6554    6.6554
      ncb20b   1000              1         0.6150    204.8902        96   26.6734            7.6814    7.6814
      nondia    100             38         0.0622      0.0007         3    0.0003            1.0000    2.1241
    penalty1  10000              1         1.0085      8.0439         2    8.0374            1.0000    1.0008
    penalty3   1000              5         0.3850      2.3934        15    2.0990            1.1403    1.1403
      quartc  10000              3         1.1315      4.2677         1    4.2661            1.0000    1.0004
     sinquad   1000             59         1.3900      0.8160        52    0.6837            1.1935    1.1935
    sparsine   1000             11         0.6119     85.4757        99   48.9996            1.7444    1.7444
    sparsqur   1000             12         0.2951      0.0910         7    0.0832            1.0000    1.0942
    srosenbr    100            100         0.0604      0.0017         4    0.0007            1.0000    2.4862
    tquartic    100             15         0.0470      0.0007         4    0.0004            1.0000    1.8827
    tquartic 100000              1         6.8175   2217.3401        75  471.3734            4.7040    4.7040
      tridia   1000              2         1.1380      2.4046        70    1.0818            2.2228    2.2228
      vardim   1000              8         0.6602     31.1869         6   31.0967            1.0000    1.0029
       woods    100             47         0.0670      0.0084         6    0.0012            1.0000    7.1968
       woods  10000              3         1.0587     11.4089        12    7.3593            1.5503    1.5503
=================================================================================================================================================

==================================================
AGGREGATE METRICS (MODEL)
==================================================
0.50   1.0000
0.75   1.5774
0.90   2.1954
--------------------------------------------------
Global Mean Perf. Ratio     : 1.6367
Geometric Mean Perf. Ratio  : 1.3584
Maximum Performance Ratio   : 7.6814
--------------------------------------------------
Total Actual Compute Time   : 4977.2098s
Total Oracle Optimal Time   : 2227.5261s
==================================================

,name,nvar,predicted_mem,predicted_time,actual_time,best_mem,best_time,performance_ratio,raw_ratio
0,arglinb,100,3,0.063660,0.000294,1,0.000229,1.000000,1.284375
1,argtrig,100,50,0.046949,0.009998,61,0.008126,1.000000,1.230349
2,arwhead,1000,47,0.384161,0.046104,3,0.040062,1.000000,1.150810
3,brownal,100,7,0.099257,0.000306,1,0.000280,1.000000,1.092845
4,brybnd,10000,20,2.125120,24.378822,1,23.019709,1.059041,1.059041
5,clplatea,961,8,0.425735,2.162715,97,1.057629,2.044871,2.044871
6,clplatec,100,100,0.075480,0.020761,87,0.012869,1.000000,1.613273
7,cosine,100,29,0.087950,0.001018,1,0.000634,1.000000,1.605867
8,cragglvy,1000,51,0.299760,0.328729,12,0.247496,1.000000,1.328218
9,cragglvy,10000,1,3.642981,31.816462,6,24.499405,1.298663,1.298663
10,cragglvy2,1000,44,0.728411,0.317482,27,0.294773,1.000000,1.077039
11,curly,100,20,0.153569,0.162793,96,0.041372,3.934852,3.934852
12,curly30,1000,2,0.500759,260.385978,99,124.836701,2.085813,2.085813
13,dixmaanf,9999,10,3.620986,326.738274,56,305.108326,1.070893,1.070893
14,dixmaang,9999,2,3.179636,341.095980,87,281.717223,1.210774,1.210774
15,dixmaani,99,31,0.050379,0.039211,96,0.035220,1.000000,1.113320
16,dixmaank,999,75,0.778378,3.148650,100,2.963739,1.062391,1.062391
17,dixmaanl,999,3,0.467080,2.373957,66,2.292193,1.000000,1.035671
18,dixmaanl,9999,3,3.798740,314.177805,32,251.754948,1.247951,1.247951
19,dixmaann,99,3,0.061420,0.136917,99,0.048629,1.000000,2.815537
20,dixmaann,999,2,0.381610,32.271045,1,20.112668,1.604513,1.604513
21,dqdrtic,1000,1,0.607998,0.089514,9,0.030697,1.000000,2.916063
22,extrosnb,100000,1,6.682021,981.899404,79,533.513211,1.840441,1.840441
23,fletcbv3_mod,10000,17,3.719344,81.071601,2,49.935938,1.623512,1.623512
24,fletchcr,1000,3,0.300738,5.698759,36,4.061515,1.403112,1.403112
25,freuroth,100,2,0.047044,0.002636,23,0.002050,1.000000,1.285880
26,genhumps,100,3,0.089765,0.106454,9,0.074535,1.000000,1.428246
27,ncb20,100,3,0.268370,0.398023,99,0.059805,6.655358,6.655358
28,ncb20b,1000,1,0.615026,204.890185,96,26.673420,7.681437,7.681437
29,nondia,100,38,0.062196,0.000657,3,0.000309,1.000000,2.124133
30,penalty1,10000,1,1.008538,8.043927,2,8.037379,1.000000,1.000815
31,penalty3,1000,5,0.385014,2.393408,15,2.098970,1.140277,1.140277
32,quartc,10000,3,1.131511,4.267688,1,4.266108,1.000000,1.000370
33,sinquad,1000,59,1.389993,0.816045,52,0.683725,1.193528,1.193528
34,sparsine,1000,11,0.611923,85.475732,99,48.999589,1.744417,1.744417
35,sparsqur,1000,12,0.295093,0.091039,7,0.083205,1.000000,1.094153
36,srosenbr,100,100,0.060373,0.001713,4,0.000689,1.000000,2.486159
37,tquartic,100,15,0.047045,0.000712,4,0.000378,1.000000,1.882724
38,tquartic,100000,1,6.817452,2217.340130,75,471.373380,4.703999,4.703999
39,tridia,1000,2,1.137993,2.404632,70,1.081799,2.222809,2.222809
40,vardim,1000,8,0.660214,31.186947,6,31.096726,1.000000,1.002901
41,woods,100,47,0.066996,0.008363,6,0.001162,1.000000,7.196758
42,woods,10000,3,1.058739,11.408949,12,7.359282,1.550280,1.550280

### Using Predicted Data from Best Stage 1 Hybrid Model For XGBoost

In [ ]:
# import numpy as np
# import pandas as pd
# import xgboost as xgb
# from scipy.stats import randint, uniform
# from sklearn.model_selection import RandomizedSearchCV

# # ==============================================================================
# # ROBUST SEARCH SPACE FOR LOG-SPACE META-MODELING
# # ==============================================================================
# param_distributions = {
#     'n_estimators':      randint(100, 500),
#     'learning_rate':     uniform(0.01, 0.15),  # Lower, stable rates to prevent variance spikes
#     'max_depth':         randint(2, 6),        # Shallow trees prevent overfitting to Stage 1 noise
#     'subsample':         uniform(0.6, 0.4),    # Stochastic sampling for generalization
#     'colsample_bytree':  uniform(0.6, 0.4),    
#     'min_child_weight':  randint(1, 10),
    
#     # Tightened structural constraints to match low-variance log targets
#     'gamma':             uniform(0, 0.1),      
#     'reg_alpha':         uniform(0, 0.1),      # L1 Regularization
#     'reg_lambda':        uniform(0.5, 1.5),    # L2 Regularization
# }

# # Utilizing hist tree method for extreme speed optimization across 5,000 total fits
# xgb_model = xgb.XGBRegressor(tree_method='hist', random_state=42, n_jobs=1)

# time_random_search = RandomizedSearchCV(
#     xgb_model,
#     param_distributions=param_distributions,
#     n_iter=1000, # 1,000 iterations across the CV loop
#     cv=5,
#     scoring='neg_mean_squared_error',
#     n_jobs=4,
#     random_state=42,
#     verbose=3,
#     return_train_score=True,
#     error_score='raise'
# )

# print("Starting 1,000-iteration Robust XGBoost Stage 2 Search...")
# print(f"Total Fits to Execute: {1000 * 5} (1000 iterations x 5 folds)\n")

# # Fit the robust model on your un-leaked out-of-fold log feature matrix
# time_random_search.fit(X_train_time, y_train_time)

# # ==============================================================================
# # PROGRESSION TRAJECTORY ANALYSIS (Print Data Along the Way)
# # ==============================================================================
# results_df = pd.DataFrame(time_random_search.cv_results_)
# results_df['actual_mse'] = -results_df['mean_test_score']

# print("\n" + "="*90)
# print("XGBOOST SEARCH-SPACE TRAJECTORY LANDSCAPE (MILESTONE INTERVALS)")
# print("="*90)
# print("Tracking hyperparameter convergence across sequential intervals:")

# # Extract performance indicators at regular milestones across the 1000 runs
# intervals = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 999]
# milestone_cols = ['actual_mse', 'mean_fit_time', 'param_n_estimators', 
#                   'param_learning_rate', 'param_max_depth', 'param_subsample',
#                   'param_reg_alpha', 'param_reg_lambda']

# sorted_by_run = results_df.copy() # Keeps the initial processing timeline visible
# print(sorted_by_run[milestone_cols].iloc[intervals].to_string(index=True))

# print("\n" + "="*80)
# print("OPTIMAL CONFIGURATION METRICS")
# print("="*80)
# print(f"Best Parameters : {time_random_search.best_params_}")
# print(f"Best Log-MSE    : {-time_random_search.best_score_:.4f}")
# print("="*80)

# # Export complete trajectory framework for performance logging
# results_df.to_csv('xgb_randomsearch_stage2_1000runs_trajectory.csv', index=False)

Starting 1,000-iteration Robust XGBoost Stage 2 Search...
Total Fits to Execute: 5000 (1000 iterations x 5 folds)

Fitting 5 folds for each of 1000 candidates, totalling 5000 fits
[CV 1/5] END colsample_bytree=0.749816047538945, gamma=0.09507143064099162, learning_rate=0.11979909127171076, max_depth=2, min_child_weight=5, n_estimators=202, reg_alpha=0.04458327528535912, reg_lambda=0.6499623737270044, subsample=0.7836995567863468;, score=(train=-0.932, test=-1.477) total time=   0.1s
[CV 2/5] END colsample_bytree=0.749816047538945, gamma=0.09507143064099162, learning_rate=0.11979909127171076, max_depth=2, min_child_weight=5, n_estimators=202, reg_alpha=0.04458327528535912, reg_lambda=0.6499623737270044, subsample=0.7836995567863468;, score=(train=-0.778, test=-2.792) total time=   0.1s
[CV 3/5] END colsample_bytree=0.749816047538945, gamma=0.09507143064099162, learning_rate=0.11979909127171076, max_depth=2, min_child_weight=5, n_estimators=202, reg_alpha=0.04458327528535912, reg_lambda=0.6499623737270044, subsample=0.7836995567863468;, score=(train=-0.856, test=-2.106) total time=   0.1s
[CV 4/5] END colsample_bytree=0.749816047538945, gamma=0.09507143064099162, learning_rate=0.11979909127171076, max_depth=2, min_child_weight=5, n_estimators=202, reg_alpha=0.04458327528535912, reg_lambda=0.6499623737270044, subsample=0.7836995567863468;, score=(train=-0.916, test=-1.362) total time=   0.1s
[CV 5/5] END colsample_bytree=0.749816047538945, gamma=0.09507143064099162, learning_rate=0.11979909127171076, max_depth=2, min_child_weight=5, n_estimators=202, reg_alpha=0.04458327528535912, reg_lambda=0.6499623737270044, subsample=0.7836995567863468;, score=(train=-0.737, test=-3.283) total time=   0.1s
[CV 1/5] END colsample_bytree=0.7334834444556088, gamma=0.014286681792194078, learning_rate=0.10763327094232793, max_depth=2, min_child_weight=2, n_estimators=443, reg_alpha=0.08324426408004218, reg_lambda=0.8185086660174142, subsample=0.6727299868828402;, score=(train=-0.752, test=-1.504) total time=   0.1s
[CV 2/5] END colsample_bytree=0.7334834444556088, gamma=0.014286681792194078, learning_rate=0.10763327094232793, max_depth=2, min_child_weight=2, n_estimators=443, reg_alpha=0.08324426408004218, reg_lambda=0.8185086660174142, subsample=0.6727299868828402;, score=(train=-0.629, test=-2.700) total time=   0.1s
[CV 3/5] END colsample_bytree=0.7334834444556088, gamma=0.014286681792194078, learning_rate=0.10763327094232793, max_depth=2, min_child_weight=2, n_estimators=443, reg_alpha=0.08324426408004218, reg_lambda=0.8185086660174142, subsample=0.6727299868828402;, score=(train=-0.690, test=-2.217) total time=   0.1s
[CV 4/5] END colsample_bytree=0.7334834444556088, gamma=0.014286681792194078, learning_rate=0.10763327094232793, max_depth=2, min_child_weight=2, n_estimators=443, reg_alpha=0.08324426408004218, reg_lambda=0.8185086660174142, subsample=0.6727299868828402;, score=(train=-0.750, test=-1.663) total time=   0.1s
[CV 1/5] END colsample_bytree=0.6733618039413735, gamma=0.030424224295953775, learning_rate=0.08871346474483567, max_depth=5, min_child_weight=9, n_estimators=148, reg_alpha=0.052477466025838915, reg_lambda=1.0997914575728833, subsample=0.6186662652854461;, score=(train=-0.389, test=-1.976) total time=   0.1s
[CV 3/5] END colsample_bytree=0.6733618039413735, gamma=0.030424224295953775, learning_rate=0.08871346474483567, max_depth=5, min_child_weight=9, n_estimators=148, reg_alpha=0.052477466025838915, reg_lambda=1.0997914575728833, subsample=0.6186662652854461;, score=(train=-0.351, test=-2.391) total time=   0.1s
[CV 5/5] END colsample_bytree=0.6733618039413735, gamma=0.030424224295953775, learning_rate=0.08871346474483567, max_depth=5, min_child_weight=9, n_estimators=148, reg_alpha=0.052477466025838915, reg_lambda=1.0997914575728833, subsample=0.6186662652854461;, score=(train=-0.306, test=-3.508) total time=   0.1s
[CV 2/5] END colsample_bytree=0.6733618039413735, gamma=0.030424224295953775, learning_rate=0.08871346474483567, max_depth=5, min_child_weight=9, n_estimators=148, reg_alpha=0.052477466025838915, reg_lambda=1.0997914575728833, subsample=0.6186662652854461;, score=(train=-0.312, test=-3.093) total time=   0.1s
[CV 4/5] END colsample_bytree=0.6733618039413735, gamma=0.030424224295953775, learning_rate=0.08871346474483567, max_depth=5, min_child_weight=9, n_estimators=148, reg_alpha=0.052477466025838915, reg_lambda=1.0997914575728833, subsample=0.6186662652854461;, score=(train=-0.364, test=-1.991) total time=   0.1s
[CV 5/5] END colsample_bytree=0.7334834444556088, gamma=0.014286681792194078, learning_rate=0.10763327094232793, max_depth=2, min_child_weight=2, n_estimators=443, reg_alpha=0.08324426408004218, reg_lambda=0.8185086660174142, subsample=0.6727299868828402;, score=(train=-0.580, test=-3.559) total time=   0.1s
[CV 1/5] END colsample_bytree=0.9895022075365837, gamma=0.023277134043030424, learning_rate=0.02359096517992312, max_depth=3, min_child_weight=3, n_estimators=463, reg_alpha=0.05142344384136116, reg_lambda=1.3886218532930636, subsample=0.6185801650879991;, score=(train=-0.803, test=-1.577) total time=   0.2s
[CV 2/5] END colsample_bytree=0.9895022075365837, gamma=0.023277134043030424, learning_rate=0.02359096517992312, max_depth=3, min_child_weight=3, n_estimators=463, reg_alpha=0.05142344384136116, reg_lambda=1.3886218532930636, subsample=0.6185801650879991;, score=(train=-0.696, test=-2.678) total time=   0.2s
[CV 4/5] END colsample_bytree=0.9895022075365837, gamma=0.023277134043030424, learning_rate=0.02359096517992312, max_depth=3, min_child_weight=3, n_estimators=463, reg_alpha=0.05142344384136116, reg_lambda=1.3886218532930636, subsample=0.6185801650879991;, score=(train=-0.792, test=-1.479) total time=   0.2s
[CV 1/5] END colsample_bytree=0.8430179407605753, gamma=0.017052412368729154, learning_rate=0.019757738947791925, max_depth=5, min_child_weight=9, n_estimators=415, reg_alpha=0.05632882178455393, reg_lambda=1.0781247538098742, subsample=0.6063865008880857;, score=(train=-0.485, test=-1.758) total time=   0.2s
[CV 3/5] END colsample_bytree=0.8430179407605753, gamma=0.017052412368729154, learning_rate=0.019757738947791925, max_depth=5, min_child_weight=9, n_estimators=415, reg_alpha=0.05632882178455393, reg_lambda=1.0781247538098742, subsample=0.6063865008880857;, score=(train=-0.441, test=-2.123) total time=   0.2s
[CV 3/5] END colsample_bytree=0.9895022075365837, gamma=0.023277134043030424, learning_rate=0.02359096517992312, max_depth=3, min_child_weight=3, n_estimators=463, reg_alpha=0.05142344384136116, reg_lambda=1.3886218532930636, subsample=0.6185801650879991;, score=(train=-0.724, test=-1.932) total time=   0.2s
[CV 5/5] END colsample_bytree=0.9895022075365837, gamma=0.023277134043030424, learning_rate=0.02359096517992312, max_depth=3, min_child_weight=3, n_estimators=463, reg_alpha=0.05142344384136116, reg_lambda=1.3886218532930636, subsample=0.6185801650879991;, score=(train=-0.610, test=-3.357) total time=   0.2s
[CV 2/5] END colsample_bytree=0.6923575302488596, gamma=0.024102546602601173, learning_rate=0.11248952782381873, max_depth=5, min_child_weight=8, n_estimators=134, reg_alpha=0.0909320402078782, reg_lambda=0.8881699724000254, subsample=0.8650089137415928;, score=(train=-0.284, test=-3.018) total time=   0.1s
[CV 2/5] END colsample_bytree=0.8430179407605753, gamma=0.017052412368729154, learning_rate=0.019757738947791925, max_depth=5, min_child_weight=9, n_estimators=415, reg_alpha=0.05632882178455393, reg_lambda=1.0781247538098742, subsample=0.6063865008880857;, score=(train=-0.392, test=-2.982) total time=   0.2s
[CV 3/5] END colsample_bytree=0.6923575302488596, gamma=0.024102546602601173, learning_rate=0.11248952782381873, max_depth=5, min_child_weight=8, n_estimators=134, reg_alpha=0.0909320402078782, reg_lambda=0.8881699724000254, subsample=0.8650089137415928;, score=(train=-0.333, test=-2.322) total time=   0.1s
[CV 4/5] END colsample_bytree=0.6923575302488596, gamma=0.024102546602601173, learning_rate=0.11248952782381873, max_depth=5, min_child_weight=8, n_estimators=134, reg_alpha=0.0909320402078782, reg_lambda=0.8881699724000254, subsample=0.8650089137415928;, score=(train=-0.347, test=-1.952) total time=   0.1s
[CV 4/5] END colsample_bytree=0.8430179407605753, gamma=0.017052412368729154, learning_rate=0.019757738947791925, max_depth=5, min_child_weight=9, n_estimators=415, reg_alpha=0.05632882178455393, reg_lambda=1.0781247538098742, subsample=0.6063865008880857;, score=(train=-0.466, test=-1.887) total time=   0.2s
[CV 5/5] END colsample_bytree=0.8430179407605753, gamma=0.017052412368729154, learning_rate=0.019757738947791925, max_depth=5, min_child_weight=9, n_estimators=415, reg_alpha=0.05632882178455393, reg_lambda=1.0781247538098742, subsample=0.6063865008880857;, score=(train=-0.372, test=-3.552) total time=   0.2s
[CV 5/5] END colsample_bytree=0.6923575302488596, gamma=0.024102546602601173, learning_rate=0.11248952782381873, max_depth=5, min_child_weight=8, n_estimators=134, reg_alpha=0.0909320402078782, reg_lambda=0.8881699724000254, subsample=0.8650089137415928;, score=(train=-0.269, test=-3.822) total time=   0.1s
[CV 1/5] END colsample_bytree=0.7246844304357644, gamma=0.05200680211778108, learning_rate=0.09200654190149193, max_depth=3, min_child_weight=2, n_estimators=317, reg_alpha=0.04497541333697657, reg_lambda=1.0927253540027215, subsample=0.9706635463175177;, score=(train=-0.541, test=-1.778) total time=   0.1s
[CV 1/5] END colsample_bytree=0.6923575302488596, gamma=0.024102546602601173, learning_rate=0.11248952782381873, max_depth=5, min_child_weight=8, n_estimators=134, reg_alpha=0.0909320402078782, reg_lambda=0.8881699724000254, subsample=0.8650089137415928;, score=(train=-0.357, test=-1.955) total time=   0.1s
[CV 3/5] END colsample_bytree=0.7246844304357644, gamma=0.05200680211778108, learning_rate=0.09200654190149193, max_depth=3, min_child_weight=2, n_estimators=317, reg_alpha=0.04497541333697657, reg_lambda=1.0927253540027215, subsample=0.9706635463175177;, score=(train=-0.501, test=-2.135) total time=   0.1s
[CV 5/5] END colsample_bytree=0.7246844304357644, gamma=0.05200680211778108, learning_rate=0.09200654190149193, max_depth=3, min_child_weight=2, n_estimators=317, reg_alpha=0.04497541333697657, reg_lambda=1.0927253540027215, subsample=0.9706635463175177;, score=(train=-0.427, test=-3.765) total time=   0.1s
[CV 2/5] END colsample_bytree=0.7246844304357644, gamma=0.05200680211778108, learning_rate=0.09200654190149193, max_depth=3, min_child_weight=2, n_estimators=317, reg_alpha=0.04497541333697657, reg_lambda=1.0927253540027215, subsample=0.9706635463175177;, score=(train=-0.451, test=-2.818) total time=   0.1s
[CV 4/5] END colsample_bytree=0.7246844304357644, gamma=0.05200680211778108, learning_rate=0.09200654190149193, max_depth=3, min_child_weight=2, n_estimators=317, reg_alpha=0.04497541333697657, reg_lambda=1.0927253540027215, subsample=0.9706635463175177;, score=(train=-0.538, test=-1.920) total time=   0.1s
[CV 2/5] END colsample_bytree=0.8909087983425683, gamma=0.03265407688058354, learning_rate=0.0955665961608099, max_depth=5, min_child_weight=9, n_estimators=289, reg_alpha=0.032533033076326434, reg_lambda=1.083015934534223, subsample=0.7085396127095583;, score=(train=-0.201, test=-2.845) total time=   0.1s
[CV 1/5] END colsample_bytree=0.8909087983425683, gamma=0.03265407688058354, learning_rate=0.0955665961608099, max_depth=5, min_child_weight=9, n_estimators=289, reg_alpha=0.032533033076326434, reg_lambda=1.083015934534223, subsample=0.7085396127095583;, score=(train=-0.240, test=-2.138) total time=   0.1s
[CV 4/5] END colsample_bytree=0.8909087983425683, gamma=0.03265407688058354, learning_rate=0.0955665961608099, max_depth=5, min_child_weight=9, n_estimators=289, reg_alpha=0.032533033076326434, reg_lambda=1.083015934534223, subsample=0.7085396127095583;, score=(train=-0.240, test=-2.202) total time=   0.1s
[CV 1/5] END colsample_bytree=0.9314950036607718, gamma=0.035675332669358926, learning_rate=0.05214017645310712, max_depth=5, min_child_weight=9, n_estimators=256, reg_alpha=0.08021969807540397, reg_lambda=0.6118259655196563, subsample=0.9947547746402069;, score=(train=-0.406, test=-1.877) total time=   0.1s
[CV 3/5] END colsample_bytree=0.8909087983425683, gamma=0.03265407688058354, learning_rate=0.0955665961608099, max_depth=5, min_child_weight=9, n_estimators=289, reg_alpha=0.032533033076326434, reg_lambda=1.083015934534223, subsample=0.7085396127095583;, score=(train=-0.216, test=-2.468) total time=   0.1s
[CV 3/5] END colsample_bytree=0.9314950036607718, gamma=0.035675332669358926, learning_rate=0.05214017645310712, max_depth=5, min_child_weight=9, n_estimators=256, reg_alpha=0.08021969807540397, reg_lambda=0.6118259655196563, subsample=0.9947547746402069;, score=(train=-0.359, test=-2.270) total time=   0.1s
[CV 2/5] END colsample_bytree=0.9314950036607718, gamma=0.035675332669358926, learning_rate=0.05214017645310712, max_depth=5, min_child_weight=9, n_estimators=256, reg_alpha=0.08021969807540397, reg_lambda=0.6118259655196563, subsample=0.9947547746402069;, score=(train=-0.310, test=-2.742) total time=   0.1s
[CV 5/5] END colsample_bytree=0.8909087983425683, gamma=0.03265407688058354, learning_rate=0.0955665961608099, max_depth=5, min_child_weight=9, n_estimators=289, reg_alpha=0.032533033076326434, reg_lambda=1.083015934534223, subsample=0.7085396127095583;, score=(train=-0.199, test=-3.667) total time=   0.1s
[CV 5/5] END colsample_bytree=0.9314950036607718, gamma=0.035675332669358926, learning_rate=0.05214017645310712, max_depth=5, min_child_weight=9, n_estimators=256, reg_alpha=0.08021969807540397, reg_lambda=0.6118259655196563, subsample=0.9947547746402069;, score=(train=-0.299, test=-3.671) total time=   0.1s
[CV 2/5] END colsample_bytree=0.908897907718663, gamma=0.019871568153417243, learning_rate=0.01082831756854036, max_depth=4, min_child_weight=3, n_estimators=180, reg_alpha=0.071134195274865, reg_lambda=1.6852633107968085, subsample=0.8423839899124046;, score=(train=-1.172, test=-3.219) total time=   0.1s
[CV 4/5] END colsample_bytree=0.908897907718663, gamma=0.019871568153417243, learning_rate=0.01082831756854036, max_depth=4, min_child_weight=3, n_estimators=180, reg_alpha=0.071134195274865, reg_lambda=1.6852633107968085, subsample=0.8423839899124046;, score=(train=-1.377, test=-1.775) total time=   0.1s
[CV 4/5] END colsample_bytree=0.9314950036607718, gamma=0.035675332669358926, learning_rate=0.05214017645310712, max_depth=5, min_child_weight=9, n_estimators=256, reg_alpha=0.08021969807540397, reg_lambda=0.6118259655196563, subsample=0.9947547746402069;, score=(train=-0.366, test=-1.981) total time=   0.1s
[CV 1/5] END colsample_bytree=0.908897907718663, gamma=0.019871568153417243, learning_rate=0.01082831756854036, max_depth=4, min_child_weight=3, n_estimators=180, reg_alpha=0.071134195274865, reg_lambda=1.6852633107968085, subsample=0.8423839899124046;, score=(train=-1.344, test=-1.795) total time=   0.1s
[CV 3/5] END colsample_bytree=0.908897907718663, gamma=0.019871568153417243, learning_rate=0.01082831756854036, max_depth=4, min_child_weight=3, n_estimators=180, reg_alpha=0.071134195274865, reg_lambda=1.6852633107968085, subsample=0.8423839899124046;, score=(train=-1.276, test=-1.826) total time=   0.1s
[CV 5/5] END colsample_bytree=0.908897907718663, gamma=0.019871568153417243, learning_rate=0.01082831756854036, max_depth=4, min_child_weight=3, n_estimators=180, reg_alpha=0.071134195274865, reg_lambda=1.6852633107968085, subsample=0.8423839899124046;, score=(train=-1.135, test=-3.393) total time=   0.1s
[CV 1/5] END colsample_bytree=0.9705203514053395, gamma=0.06510770255019445, learning_rate=0.14724395133156712, max_depth=2, min_child_weight=8, n_estimators=367, reg_alpha=0.03308980248526492, reg_lambda=0.5953375254290354, subsample=0.7243929286862649;, score=(train=-0.728, test=-1.493) total time=   0.1s
[CV 3/5] END colsample_bytree=0.9705203514053395, gamma=0.06510770255019445, learning_rate=0.14724395133156712, max_depth=2, min_child_weight=8, n_estimators=367, reg_alpha=0.03308980248526492, reg_lambda=0.5953375254290354, subsample=0.7243929286862649;, score=(train=-0.668, test=-2.207) total time=   0.1s
[CV 5/5] END colsample_bytree=0.9705203514053395, gamma=0.06510770255019445, learning_rate=0.14724395133156712, max_depth=2, min_child_weight=8, n_estimators=367, reg_alpha=0.03308980248526492, reg_lambda=0.5953375254290354, subsample=0.7243929286862649;, score=(train=-0.562, test=-3.516) total time=   0.1s
[CV 2/5] END colsample_bytree=0.7300733288106989, gamma=0.0729606178338064, learning_rate=0.10563362070328196, max_depth=4, min_child_weight=3, n_estimators=326, reg_alpha=0.01195942459383017, reg_lambda=1.5698671808344926, subsample=0.9043140194467589;, score=(train=-0.250, test=-2.993) total time=   0.1s
[CV 2/5] END colsample_bytree=0.9705203514053395, gamma=0.06510770255019445, learning_rate=0.14724395133156712, max_depth=2, min_child_weight=8, n_estimators=367, reg_alpha=0.03308980248526492, reg_lambda=0.5953375254290354, subsample=0.7243929286862649;, score=(train=-0.608, test=-2.750) total time=   0.1s
[CV 4/5] END colsample_bytree=0.9705203514053395, gamma=0.06510770255019445, learning_rate=0.14724395133156712, max_depth=2, min_child_weight=8, n_estimators=367, reg_alpha=0.03308980248526492, reg_lambda=0.5953375254290354, subsample=0.7243929286862649;, score=(train=-0.714, test=-1.626) total time=   0.1s
[CV 1/5] END colsample_bytree=0.7300733288106989, gamma=0.0729606178338064, learning_rate=0.10563362070328196, max_depth=4, min_child_weight=3, n_estimators=326, reg_alpha=0.01195942459383017, reg_lambda=1.5698671808344926, subsample=0.9043140194467589;, score=(train=-0.308, test=-2.003) total time=   0.1s
[CV 1/5] END colsample_bytree=0.8245108790277985, gamma=0.0770967179954561, learning_rate=0.08406933945465861, max_depth=2, min_child_weight=3, n_estimators=162, reg_alpha=0.08957635956735194, reg_lambda=1.2130553347731676, subsample=0.8253102287905535;, score=(train=-1.091, test=-1.568) total time=   0.0s
[CV 3/5] END colsample_bytree=0.7300733288106989, gamma=0.0729606178338064, learning_rate=0.10563362070328196, max_depth=4, min_child_weight=3, n_estimators=326, reg_alpha=0.01195942459383017, reg_lambda=1.5698671808344926, subsample=0.9043140194467589;, score=(train=-0.280, test=-2.464) total time=   0.1s
[CV 4/5] END colsample_bytree=0.7300733288106989, gamma=0.0729606178338064, learning_rate=0.10563362070328196, max_depth=4, min_child_weight=3, n_estimators=326, reg_alpha=0.01195942459383017, reg_lambda=1.5698671808344926, subsample=0.9043140194467589;, score=(train=-0.299, test=-1.978) total time=   0.1s
[CV 3/5] END colsample_bytree=0.8245108790277985, gamma=0.0770967179954561, learning_rate=0.08406933945465861, max_depth=2, min_child_weight=3, n_estimators=162, reg_alpha=0.08957635956735194, reg_lambda=1.2130553347731676, subsample=0.8253102287905535;, score=(train=-1.025, test=-1.962) total time=   0.0s
[CV 2/5] END colsample_bytree=0.8245108790277985, gamma=0.0770967179954561, learning_rate=0.08406933945465861, max_depth=2, min_child_weight=3, n_estimators=162, reg_alpha=0.08957635956735194, reg_lambda=1.2130553347731676, subsample=0.8253102287905535;, score=(train=-0.950, test=-2.665) total time=   0.0s
[CV 5/5] END colsample_bytree=0.8245108790277985, gamma=0.0770967179954561, learning_rate=0.08406933945465861, max_depth=2, min_child_weight=3, n_estimators=162, reg_alpha=0.08957635956735194, reg_lambda=1.2130553347731676, subsample=0.8253102287905535;, score=(train=-0.876, test=-3.173) total time=   0.0s
[CV 4/5] END colsample_bytree=0.8245108790277985, gamma=0.0770967179954561, learning_rate=0.08406933945465861, max_depth=2, min_child_weight=3, n_estimators=162, reg_alpha=0.08957635956735194, reg_lambda=1.2130553347731676, subsample=0.8253102287905535;, score=(train=-1.102, test=-1.211) total time=   0.0s

In [383]:
time_best_model_gb = joblib.load('./model_weights/best_hybrid_xgb_model_time_new_cv.pkl')
# time_best_model_gb = time_random_search.best_estimator_
accuracy = time_best_model_gb.score(X_test_time, y_test_time)
print(f"Time prediction accuracy based on predicted values={accuracy}")

# joblib.dump(time_best_model_gb, './model_weights/best_hybrid_xgb_model_time_new_cv.pkl')

Time prediction accuracy based on predicted values=0.5659815122354326

In [384]:
pred = time_best_model_gb.predict(X_test_time)
test_mse = mean_squared_error(y_test_time, pred)
test_r2  = r2_score(y_test_time, pred)
print(f"MSE={test_mse:.4f}  R²={test_r2:.4f}")

# Compute pointwise relative error matching the paper's formula: |y - y_hat| / (|y| + delta)
relative_error = np.abs(pred - y_test_time) / (np.abs(y_test_time) + 1e-8)

# Quantiled Relative Error Distribution
quantiles = [0.25, 0.50, 0.75]
print("\n--- Quantiled Relative Error Q(q) (Test Set) ---")
for i, col in enumerate(target_col_model):
    print(f"\n{col}:")
    print(f"Quantile (q) | Relative Error Value Q(q)")
    
    # Safe extraction whether relative_error is a 1D vector or a 2D column matrix
    error_data = relative_error[:, i] if relative_error.ndim > 1 else relative_error
    q_values = np.quantile(error_data, quantiles)
    
    for q, val in zip(quantiles, q_values):
        print(f"  Q({q:.2f}):  {val:.4f}")

MSE=1.9602  R²=0.5660

--- Quantiled Relative Error Q(q) (Test Set) ---

stats_elapsed_time:
Quantile (q) | Relative Error Value Q(q)
  Q(0.25):  0.4016
  Q(0.50):  0.8059
  Q(0.75):  18.4072

In [385]:
evaluate_model(joblib.load('./model_weights/best_hybrid_xgb_model_time_new_cv.pkl'))

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (MODEL)
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100              2         0.0820      0.0003         1    0.0002            1.0000    1.2844
     argtrig    100             70         0.0820      0.0180        61    0.0081            1.0000    2.2172
     arwhead   1000              3         0.7408      0.0401         3    0.0401            1.0000    1.0000
     brownal    100              1         0.2182      0.0003         1    0.0003            1.0000    1.0000
      brybnd  10000             11         3.5098     24.3659         1   23.0197            1.0585    1.0585
    clplatea    961             12         0.7615      2.0763        97    1.0576            1.9631    1.9631
    clplatec    100             67        -0.6387      0.0177        87    0.0129            1.0000    1.3763
      cosine    100              1        -0.1049      0.0006         1    0.0006            1.0000    1.0000
    cragglvy   1000              3         0.8266      0.3104        12    0.2475            1.0000    1.2543
    cragglvy  10000              3         1.8118     27.0828         6   24.4994            1.1054    1.1054
   cragglvy2   1000             22         0.9583      0.3079        27    0.2948            1.0000    1.0445
       curly    100             17        -0.0558      0.0984        96    0.0414            1.0000    2.3778
     curly30   1000              2         0.5844    260.3860        99  124.8367            2.0858    2.0858
    dixmaanf   9999             27         2.9238    320.0591        56  305.1083            1.0490    1.0490
    dixmaang   9999              9         2.4303    308.7570        87  281.7172            1.0960    1.0960
    dixmaani     99              1         0.0820      0.0719        96    0.0352            1.0000    2.0428
    dixmaank    999              3         0.7562      3.5363       100    2.9637            1.1932    1.1932
    dixmaanl    999              3         0.6705      2.3740        66    2.2922            1.0000    1.0357
    dixmaanl   9999             27         2.9175    266.8155        32  251.7549            1.0598    1.0598
    dixmaann     99             22         0.0820      0.0598        99    0.0486            1.0000    1.2305
    dixmaann    999              3         0.6764     27.8462         1   20.1127            1.3845    1.3845
     dqdrtic   1000              1         0.8171      0.0895         9    0.0307            1.0000    2.9161
    extrosnb 100000              1         5.2150    981.8994        79  533.5132            1.8404    1.8404
fletcbv3_mod  10000              1         3.6745     64.7788         2   49.9359            1.2972    1.2972
    fletchcr   1000              3         0.5899      5.6988        36    4.0615            1.4031    1.4031
    freuroth    100              2         0.0820      0.0026        23    0.0020            1.0000    1.2859
    genhumps    100              2        -0.1049      0.0824         9    0.0745            1.0000    1.1059
       ncb20    100              6         0.0466      0.2676        99    0.0598            4.4745    4.4745
      ncb20b   1000              2         0.9763    147.9022        96   26.6734            5.5449    5.5449
      nondia    100              1        -0.1049      0.0004         3    0.0003            1.0000    1.2614
    penalty1  10000              3         1.1384      8.0388         2    8.0374            1.0000    1.0002
    penalty3   1000             12         0.8663      2.2297        15    2.0990            1.0623    1.0623
      quartc  10000              5         1.2052      4.2665         1    4.2661            1.0000    1.0001
     sinquad   1000             30         1.1068      0.8860        52    0.6837            1.2958    1.2958
    sparsine   1000              3         0.7622    162.6173        99   48.9996            3.3187    3.3187
    sparsqur   1000              1         0.6106      0.1015         7    0.0832            1.0000    1.2201
    srosenbr    100             10        -0.5847      0.0014         4    0.0007            1.0000    2.0391
    tquartic    100             24         0.0820      0.0007         4    0.0004            1.0000    1.9098
    tquartic 100000              1         5.2235   2217.3401        75  471.3734            4.7040    4.7040
      tridia   1000             25         1.4973      1.3579        70    1.0818            1.2552    1.2552
      vardim   1000              5         0.9571     31.1121         6   31.0967            1.0000    1.0005
       woods    100              2         0.0820      0.0025         6    0.0012            1.0000    2.1514
       woods  10000              3         0.9322     11.4089        12    7.3593            1.5503    1.5503
=================================================================================================================================================

==================================================
AGGREGATE METRICS (MODEL)
==================================================
0.50   1.0000
0.75   1.2965
0.90   2.0613
--------------------------------------------------
Global Mean Perf. Ratio     : 1.4591
Geometric Mean Perf. Ratio  : 1.2742
Maximum Performance Ratio   : 5.5449
--------------------------------------------------
Total Actual Compute Time   : 4884.3097s
Total Oracle Optimal Time   : 2227.5261s
==================================================

,name,nvar,predicted_mem,predicted_time,actual_time,best_mem,best_time,performance_ratio,raw_ratio
0,arglinb,100,2,0.081954,0.000294,1,0.000229,1.000000,1.284375
1,argtrig,100,70,0.081954,0.018017,61,0.008126,1.000000,2.217205
2,arwhead,1000,3,0.740786,0.040062,3,0.040062,1.000000,1.000000
3,brownal,100,1,0.218215,0.000280,1,0.000280,1.000000,1.000000
4,brybnd,10000,11,3.509773,24.365939,1,23.019709,1.058482,1.058482
5,clplatea,961,12,0.761547,2.076262,97,1.057629,1.963129,1.963129
6,clplatec,100,67,-0.638743,0.017711,87,0.012869,1.000000,1.376260
7,cosine,100,1,-0.104909,0.000634,1,0.000634,1.000000,1.000000
8,cragglvy,1000,3,0.826571,0.310437,12,0.247496,1.000000,1.254311
9,cragglvy,10000,3,1.811823,27.082774,6,24.499405,1.105446,1.105446
10,cragglvy2,1000,22,0.958265,0.307899,27,0.294773,1.000000,1.044529
11,curly,100,17,-0.055830,0.098375,96,0.041372,1.000000,2.377814
12,curly30,1000,2,0.584384,260.385978,99,124.836701,2.085813,2.085813
13,dixmaanf,9999,27,2.923783,320.059130,56,305.108326,1.049002,1.049002
14,dixmaang,9999,9,2.430290,308.756976,87,281.717223,1.095982,1.095982
15,dixmaani,99,1,0.081954,0.071946,96,0.035220,1.000000,2.042762
16,dixmaank,999,3,0.756248,3.536268,100,2.963739,1.193178,1.193178
17,dixmaanl,999,3,0.670463,2.373957,66,2.292193,1.000000,1.035671
18,dixmaanl,9999,27,2.917473,266.815523,32,251.754948,1.059822,1.059822
19,dixmaann,99,22,0.081954,0.059837,99,0.048629,1.000000,1.230476
20,dixmaann,999,3,0.676415,27.846187,1,20.112668,1.384510,1.384510
21,dqdrtic,1000,1,0.817063,0.089514,9,0.030697,1.000000,2.916063
22,extrosnb,100000,1,5.215009,981.899404,79,533.513211,1.840441,1.840441
23,fletcbv3_mod,10000,1,3.674534,64.778801,2,49.935938,1.297238,1.297238
24,fletchcr,1000,3,0.589862,5.698759,36,4.061515,1.403112,1.403112
25,freuroth,100,2,0.081954,0.002636,23,0.002050,1.000000,1.285880
26,genhumps,100,2,-0.104909,0.082425,9,0.074535,1.000000,1.105859
27,ncb20,100,6,0.046643,0.267597,99,0.059805,4.474498,4.474498
28,ncb20b,1000,2,0.976346,147.902160,96,26.673420,5.544927,5.544927
29,nondia,100,1,-0.104909,0.000390,3,0.000309,1.000000,1.261372
30,penalty1,10000,3,1.138382,8.038810,2,8.037379,1.000000,1.000178
31,penalty3,1000,12,0.866335,2.229731,15,2.098970,1.062298,1.062298
32,quartc,10000,5,1.205233,4.266530,1,4.266108,1.000000,1.000099
33,sinquad,1000,30,1.106838,0.885973,52,0.683725,1.295803,1.295803
34,sparsine,1000,3,0.762200,162.617292,99,48.999589,3.318748,3.318748
35,sparsqur,1000,1,0.610647,0.101515,7,0.083205,1.000000,1.220057
36,srosenbr,100,10,-0.584661,0.001405,4,0.000689,1.000000,2.039100
37,tquartic,100,24,0.081954,0.000722,4,0.000378,1.000000,1.909836
38,tquartic,100000,1,5.223509,2217.340130,75,471.373380,4.703999,4.703999
39,tridia,1000,25,1.497254,1.357895,70,1.081799,1.255219,1.255219
40,vardim,1000,5,0.957131,31.112093,6,31.096726,1.000000,1.000494
41,woods,100,2,0.081954,0.002500,6,0.001162,1.000000,2.151416
42,woods,10000,3,0.932250,11.408949,12,7.359282,1.550280,1.550280

## Use Pre-trained Stage 2 Models From Our Empirical Dataset directly to predict time from Best Stage 1 Hybrid Predicted Features

In [433]:
y_train_time = np.log1p(train_df[target_col_model].to_numpy(dtype=float)).ravel()
y_test_time = np.log1p(test_df[target_col_model].to_numpy(dtype=float)).ravel()

### Try Pre-Trained Stage 2 Linear Regression Model

In [434]:
# Load the saved model
lr_stage2 = joblib.load("./model_weights/best_lr_model_time.pkl")

# Use the LOADED model instance to predict
pred_log = lr_stage2.predict(X_test_time)

test_mse = mean_squared_error(y_test_time, pred_log)
test_r2 = r2_score(y_test_time, pred_log)

print("\n--- Final Test Set Metrics (Original Physical Scale) ---")
print(f"MSE = {test_mse:.4f} | R² = {test_r2:.4f}")

# 4. Quantiled Relative Error Distribution (Original Scale)
relative_error = np.abs(pred_log - y_test_time) / (np.abs(y_test_time) + 1e-8)

quantiles = [0.25, 0.50, 0.75]
print("\n--- Quantiled Relative Error Q(q) (Test Set) ---")
print(f"{target_col_model}:")
print(f"Quantile (q) | Relative Error Value Q(q)")

q_values = np.quantile(relative_error, quantiles)
for q, val in zip(quantiles, q_values):
    print(f"  Q({q:.2f}):  {val:.4f}")

--- Final Test Set Metrics (Original Physical Scale) ---
MSE = 4.5620 | R² = -0.0101

--- Quantiled Relative Error Q(q) (Test Set) ---
['stats_elapsed_time']:
Quantile (q) | Relative Error Value Q(q)
  Q(0.25):  0.5209
  Q(0.50):  1.4777
  Q(0.75):  54.0398

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [404]:
evaluate_model(joblib.load("./model_weights/best_lr_model_time.pkl"))

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (MODEL)
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100              1         2.0109      0.0002         1    0.0002            1.0000    1.0000
     argtrig    100             38         2.0108      0.0104        61    0.0081            1.0000    1.2835
     arwhead   1000             69         2.0109      0.0460         3    0.0401            1.0000    1.1473
     brownal    100              1         2.0109      0.0003         1    0.0003            1.0000    1.0000
      brybnd  10000              1         2.0109     23.0197         1   23.0197            1.0000    1.0000
    clplatea    961              8         2.0108      2.1627        97    1.0576            2.0449    2.0449
    clplatec    100             46         2.0108      0.0242        87    0.0129            1.0000    1.8779
      cosine    100             40         2.0108      0.0010         1    0.0006            1.0000    1.6183
    cragglvy   1000             36         2.0108      0.3193        12    0.2475            1.0000    1.2901
    cragglvy  10000             36         2.0108     34.8766         6   24.4994            1.4236    1.4236
   cragglvy2   1000             28         2.0108      0.3117        27    0.2948            1.0000    1.0576
       curly    100             25         2.0108      0.1225        96    0.0414            1.0000    2.9607
     curly30   1000              7         2.0109    157.9469        99  124.8367            1.2652    1.2652
    dixmaanf   9999             73         2.0108    321.6339        56  305.1083            1.0542    1.0542
    dixmaang   9999             68         2.0108    295.5870        87  281.7172            1.0492    1.0492
    dixmaani     99             37         2.0109      0.0402        96    0.0352            1.0000    1.1422
    dixmaank    999             59         2.0108      3.3501       100    2.9637            1.1304    1.1304
    dixmaanl    999             68         2.0108      2.4436        66    2.2922            1.0661    1.0661
    dixmaanl   9999             67         2.0108    269.0961        32  251.7549            1.0689    1.0689
    dixmaann     99             70         2.0108      0.0530        99    0.0486            1.0000    1.0902
    dixmaann    999             67         2.0108     37.9949         1   20.1127            1.8891    1.8891
     dqdrtic   1000             30         2.0109      0.0307         9    0.0307            1.0000    1.0014
    extrosnb 100000              1         2.0109    981.8994        79  533.5132            1.8404    1.8404
fletcbv3_mod  10000              4         2.0108     55.3543         2   49.9359            1.1085    1.1085
    fletchcr   1000             37         2.0108      4.9915        36    4.0615            1.2290    1.2290
    freuroth    100             97         2.0108      0.0031        23    0.0020            1.0000    1.5156
    genhumps    100             83         2.0108      0.1655         9    0.0745            1.0000    2.2205
       ncb20    100             21         2.0108      0.1058        99    0.0598            1.0000    1.7699
      ncb20b   1000             24         2.0108     54.5212        96   26.6734            2.0440    2.0440
      nondia    100             97         2.0108      0.0007         3    0.0003            1.0000    2.1473
    penalty1  10000             98         2.0109      8.0456         2    8.0374            1.0000    1.0010
    penalty3   1000              1         2.0109     30.2565        15    2.0990           14.4149   14.4149
      quartc  10000              1         2.0109      4.2661         1    4.2661            1.0000    1.0000
     sinquad   1000             35         2.0108      0.7693        52    0.6837            1.0000    1.1252
    sparsine   1000             56         2.0108     55.4346        99   48.9996            1.1313    1.1313
    sparsqur   1000             34         2.0109      0.1426         7    0.0832            1.0000    1.7134
    srosenbr    100             35         2.0109      0.0017         4    0.0007            1.0000    2.4062
    tquartic    100             24         2.0109      0.0007         4    0.0004            1.0000    1.9098
    tquartic 100000              1         2.0109   2217.3401        75  471.3734            4.7040    4.7040
      tridia   1000              1         2.0109      3.1661        70    1.0818            2.9267    2.9267
      vardim   1000              1         2.0109     31.1406         6   31.0967            1.0000    1.0014
       woods    100             51         2.0109      0.0031         6    0.0012            1.0000    2.7029
       woods  10000             45         2.0109      7.7637        12    7.3593            1.0550    1.0550
=================================================================================================================================================

==================================================
AGGREGATE METRICS (MODEL)
==================================================
0.50   1.0000
0.75   1.1308
0.90   2.0130
--------------------------------------------------
Global Mean Perf. Ratio     : 1.5685
Geometric Mean Perf. Ratio  : 1.2442
Maximum Performance Ratio   : 14.4149
--------------------------------------------------
Total Actual Compute Time   : 4604.4434s
Total Oracle Optimal Time   : 2227.5261s
==================================================

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

,name,nvar,predicted_mem,predicted_time,actual_time,best_mem,best_time,performance_ratio,raw_ratio
0,arglinb,100,1,2.010929,0.000229,1,0.000229,1.000000,1.000000
1,argtrig,100,38,2.010849,0.010430,61,0.008126,1.000000,1.283543
2,arwhead,1000,69,2.010870,0.045964,3,0.040062,1.000000,1.147316
3,brownal,100,1,2.010898,0.000280,1,0.000280,1.000000,1.000000
4,brybnd,10000,1,2.010871,23.019709,1,23.019709,1.000000,1.000000
5,clplatea,961,8,2.010831,2.162715,97,1.057629,2.044871,2.044871
6,clplatec,100,46,2.010843,0.024167,87,0.012869,1.000000,1.877946
7,cosine,100,40,2.010846,0.001026,1,0.000634,1.000000,1.618278
8,cragglvy,1000,36,2.010849,0.319299,12,0.247496,1.000000,1.290117
9,cragglvy,10000,36,2.010843,34.876608,6,24.499405,1.423570,1.423570
10,cragglvy2,1000,28,2.010837,0.311745,27,0.294773,1.000000,1.057576
11,curly,100,25,2.010840,0.122492,96,0.041372,1.000000,2.960744
12,curly30,1000,7,2.010908,157.946865,99,124.836701,1.265228,1.265228
13,dixmaanf,9999,73,2.010827,321.633886,56,305.108326,1.054163,1.054163
14,dixmaang,9999,68,2.010820,295.586966,87,281.717223,1.049233,1.049233
15,dixmaani,99,37,2.010853,0.040229,96,0.035220,1.000000,1.142219
16,dixmaank,999,59,2.010822,3.350086,100,2.963739,1.130358,1.130358
17,dixmaanl,999,68,2.010824,2.443637,66,2.292193,1.066069,1.066069
18,dixmaanl,9999,67,2.010825,269.096142,32,251.754948,1.068881,1.068881
19,dixmaann,99,70,2.010823,0.053016,99,0.048629,1.000000,1.090212
20,dixmaann,999,67,2.010822,37.994922,1,20.112668,1.889104,1.889104
21,dqdrtic,1000,30,2.010878,0.030739,9,0.030697,1.000000,1.001375
22,extrosnb,100000,1,2.010916,981.899404,79,533.513211,1.840441,1.840441
23,fletcbv3_mod,10000,4,2.010848,55.354259,2,49.935938,1.108505,1.108505
24,fletchcr,1000,37,2.010846,4.991486,36,4.061515,1.228972,1.228972
25,freuroth,100,97,2.010840,0.003107,23,0.002050,1.000000,1.515585
26,genhumps,100,83,2.010840,0.165505,9,0.074535,1.000000,2.220503
27,ncb20,100,21,2.010848,0.105846,99,0.059805,1.000000,1.769853
28,ncb20b,1000,24,2.010832,54.521219,96,26.673420,2.044028,2.044028
29,nondia,100,97,2.010848,0.000664,3,0.000309,1.000000,2.147263
30,penalty1,10000,98,2.010891,8.045576,2,8.037379,1.000000,1.001020
31,penalty3,1000,1,2.010855,30.256496,15,2.098970,14.414926,14.414926
32,quartc,10000,1,2.010925,4.266108,1,4.266108,1.000000,1.000000
33,sinquad,1000,35,2.010838,0.769325,52,0.683725,1.000000,1.125196
34,sparsine,1000,56,2.010847,55.434598,99,48.999589,1.131328,1.131328
35,sparsqur,1000,34,2.010869,0.142560,7,0.083205,1.000000,1.713359
36,srosenbr,100,35,2.010867,0.001658,4,0.000689,1.000000,2.406228
37,tquartic,100,24,2.010854,0.000722,4,0.000378,1.000000,1.909836
38,tquartic,100000,1,2.010911,2217.340130,75,471.373380,4.703999,4.703999
39,tridia,1000,1,2.010866,3.166102,70,1.081799,2.926701,2.926701
40,vardim,1000,1,2.010853,31.140561,6,31.096726,1.000000,1.001410
41,woods,100,51,2.010852,0.003141,6,0.001162,1.000000,2.702913
42,woods,10000,45,2.010895,7.763740,12,7.359282,1.054959,1.054959

### Try Pre-Trained Stage 2 Random Forest

In [435]:
# Load the saved model
rf_stage2 = joblib.load("./model_weights/best_rf_model_time_raw.pkl")

# Use the LOADED model instance to predict
pred_log = rf_stage2.predict(X_test_time)

test_mse = mean_squared_error(y_test_time, pred_log)
test_r2 = r2_score(y_test_time, pred_log)

print("\n--- Final Test Set Metrics (Original Physical Scale) ---")
print(f"MSE = {test_mse:.4f} | R² = {test_r2:.4f}")

# 4. Quantiled Relative Error Distribution (Original Scale)
relative_error = np.abs(pred_log - y_test_time) / (np.abs(y_test_time) + 1e-8)

quantiles = [0.25, 0.50, 0.75]
print("\n--- Quantiled Relative Error Q(q) (Test Set) ---")
print(f"{target_col_model}:")
print(f"Quantile (q) | Relative Error Value Q(q)")

q_values = np.quantile(relative_error, quantiles)
for q, val in zip(quantiles, q_values):
    print(f"  Q({q:.2f}):  {val:.4f}")

--- Final Test Set Metrics (Original Physical Scale) ---
MSE = 4.4933 | R² = 0.0051

--- Quantiled Relative Error Q(q) (Test Set) ---
['stats_elapsed_time']:
Quantile (q) | Relative Error Value Q(q)
  Q(0.25):  0.5080
  Q(0.50):  2.1647
  Q(0.75):  52.4424

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [406]:
evaluate_model(joblib.load("./model_weights/best_rf_model_time_raw.pkl"))

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (MODEL)
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100            100         1.8372      0.0003         1    0.0002            1.0000    1.2667
     argtrig    100            100         1.8450      0.0092        61    0.0081            1.0000    1.1280
     arwhead   1000            100         1.8450      0.0460         3    0.0401            1.0000    1.1480
     brownal    100            100         1.8372      0.0006         1    0.0003            1.0000    1.9787
      brybnd  10000              6         1.8372     24.3875         1   23.0197            1.0594    1.0594
    clplatea    961              9         2.5742      2.3199        97    1.0576            2.1935    2.1935
    clplatec    100            100         1.8372      0.0208        87    0.0129            1.0000    1.6133
      cosine    100            100         2.1125      0.0102         1    0.0006            1.0000   16.0673
    cragglvy   1000            100         1.8450      0.3387        12    0.2475            1.0000    1.3683
    cragglvy  10000             34         1.8372     33.1306         6   24.4994            1.3523    1.3523
   cragglvy2   1000            100         2.1304      0.3275        27    0.2948            1.0000    1.1109
       curly    100            100         2.4548      0.0464        96    0.0414            1.0000    1.1222
     curly30   1000             99         2.0429    124.8367        99  124.8367            1.0000    1.0000
    dixmaanf   9999              5         2.1304    314.4470        56  305.1083            1.0306    1.0306
    dixmaang   9999            100         2.1304    301.0419        87  281.7172            1.0686    1.0686
    dixmaani     99            100         1.8372      0.0378        96    0.0352            1.0000    1.0745
    dixmaank    999            100         2.1304      2.9637       100    2.9637            1.0000    1.0000
    dixmaanl    999            100         2.1304      2.4082        66    2.2922            1.0506    1.0506
    dixmaanl   9999              8         2.1304    266.7422        32  251.7549            1.0595    1.0595
    dixmaann     99            100         1.8450      0.0559        99    0.0486            1.0000    1.1504
    dixmaann    999            100         2.4548     39.1586         1   20.1127            1.9470    1.9470
     dqdrtic   1000            100         1.8372      0.0308         9    0.0307            1.0000    1.0019
    extrosnb 100000            100         1.7468    657.8357        79  533.5132            1.2330    1.2330
fletcbv3_mod  10000             10         1.8372     68.8640         2   49.9359            1.3790    1.3790
    fletchcr   1000             21         2.5742      4.6980        36    4.0615            1.1567    1.1567
    freuroth    100            100         1.8372      0.0031        23    0.0020            1.0000    1.5366
    genhumps    100            100         1.8450      0.1849         9    0.0745            2.4802    2.4802
       ncb20    100            100         2.4548      0.0653        99    0.0598            1.0000    1.0926
      ncb20b   1000              4         2.4548    100.0779        96   26.6734            3.7520    3.7520
      nondia    100            100         1.8450      0.0007         3    0.0003            1.0000    2.1928
    penalty1  10000            100         1.8372      8.0709         2    8.0374            1.0000    1.0042
    penalty3   1000            100         2.5742      2.3161        15    2.0990            1.1034    1.1034
      quartc  10000            100         1.7468      4.4665         1    4.2661            1.0470    1.0470
     sinquad   1000             70         2.4548      1.2802        52    0.6837            1.8724    1.8724
    sparsine   1000            100         2.4548     51.3243        99   48.9996            1.0474    1.0474
    sparsqur   1000            100         2.1125      0.1433         7    0.0832            1.0000    1.7226
    srosenbr    100            100         1.7468      0.0017         4    0.0007            1.0000    2.4862
    tquartic    100            100         1.8372      0.0007         4    0.0004            1.0000    1.9622
    tquartic 100000            100         1.7468    578.0300        75  471.3734            1.2263    1.2263
      tridia   1000             84         2.5067      1.1371        70    1.0818            1.0000    1.0511
      vardim   1000            100         2.4548     31.2277         6   31.0967            1.0042    1.0042
       woods    100            100         1.8372      0.0032         6    0.0012            1.0000    2.7522
       woods  10000            100         1.8372      7.7592        12    7.3593            1.0543    1.0543
=================================================================================================================================================

==================================================
AGGREGATE METRICS (MODEL)
==================================================
0.50   1.0000
0.75   1.0860
0.90   1.7738
--------------------------------------------------
Global Mean Perf. Ratio     : 1.2120
Geometric Mean Perf. Ratio  : 1.1498
Maximum Performance Ratio   : 3.7520
--------------------------------------------------
Total Actual Compute Time   : 2629.8511s
Total Oracle Optimal Time   : 2227.5261s
==================================================

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

,name,nvar,predicted_mem,predicted_time,actual_time,best_mem,best_time,performance_ratio,raw_ratio
0,arglinb,100,100,1.837173,0.000290,1,0.000229,1.000000,1.266667
1,argtrig,100,100,1.844965,0.009166,61,0.008126,1.000000,1.127982
2,arwhead,1000,100,1.844965,0.045992,3,0.040062,1.000000,1.148013
3,brownal,100,100,1.837173,0.000554,1,0.000280,1.000000,1.978705
4,brybnd,10000,6,1.837173,24.387542,1,23.019709,1.059420,1.059420
5,clplatea,961,9,2.574159,2.319937,97,1.057629,2.193527,2.193527
6,clplatec,100,100,1.837173,0.020761,87,0.012869,1.000000,1.613273
7,cosine,100,100,2.112496,0.010186,1,0.000634,1.000000,16.067319
8,cragglvy,1000,100,1.844965,0.338653,12,0.247496,1.000000,1.368317
9,cragglvy,10000,34,1.837173,33.130567,6,24.499405,1.352301,1.352301
10,cragglvy2,1000,100,2.130371,0.327460,27,0.294773,1.000000,1.110888
11,curly,100,100,2.454751,0.046426,96,0.041372,1.000000,1.122154
12,curly30,1000,99,2.042890,124.836701,99,124.836701,1.000000,1.000000
13,dixmaanf,9999,5,2.130371,314.446995,56,305.108326,1.030608,1.030608
14,dixmaang,9999,100,2.130371,301.041943,87,281.717223,1.068596,1.068596
15,dixmaani,99,100,1.837173,0.037843,96,0.035220,1.000000,1.074477
16,dixmaank,999,100,2.130371,2.963739,100,2.963739,1.000000,1.000000
17,dixmaanl,999,100,2.130371,2.408196,66,2.292193,1.050608,1.050608
18,dixmaanl,9999,8,2.130371,266.742175,32,251.754948,1.059531,1.059531
19,dixmaann,99,100,1.844965,0.055941,99,0.048629,1.000000,1.150364
20,dixmaann,999,100,2.454751,39.158556,1,20.112668,1.946960,1.946960
21,dqdrtic,1000,100,1.837173,0.030756,9,0.030697,1.000000,1.001926
22,extrosnb,100000,100,1.746795,657.835676,79,533.513211,1.233026,1.233026
23,fletcbv3_mod,10000,10,1.837173,68.864040,2,49.935938,1.379048,1.379048
24,fletchcr,1000,21,2.574159,4.697989,36,4.061515,1.156709,1.156709
25,freuroth,100,100,1.837173,0.003150,23,0.002050,1.000000,1.536636
26,genhumps,100,100,1.844965,0.184860,9,0.074535,2.480181,2.480181
27,ncb20,100,100,2.454751,0.065345,99,0.059805,1.000000,1.092633
28,ncb20b,1000,4,2.454751,100.077912,96,26.673420,3.751972,3.751972
29,nondia,100,100,1.844965,0.000678,3,0.000309,1.000000,2.192753
30,penalty1,10000,100,1.837173,8.070869,2,8.037379,1.000000,1.004167
31,penalty3,1000,100,2.574159,2.316102,15,2.098970,1.103447,1.103447
32,quartc,10000,100,1.746795,4.466477,1,4.266108,1.046968,1.046968
33,sinquad,1000,70,2.454751,1.280226,52,0.683725,1.872428,1.872428
34,sparsine,1000,100,2.454751,51.324333,99,48.999589,1.047444,1.047444
35,sparsqur,1000,100,2.112496,0.143327,7,0.083205,1.000000,1.722577
36,srosenbr,100,100,1.746795,0.001713,4,0.000689,1.000000,2.486159
37,tquartic,100,100,1.837173,0.000742,4,0.000378,1.000000,1.962169
38,tquartic,100000,100,1.746795,578.029979,75,471.373380,1.226268,1.226268
39,tridia,1000,84,2.506744,1.137120,70,1.081799,1.000000,1.051138
40,vardim,1000,100,2.454751,31.227748,6,31.096726,1.004213,1.004213
41,woods,100,100,1.837173,0.003198,6,0.001162,1.000000,2.752154
42,woods,10000,100,1.837173,7.759227,12,7.359282,1.054346,1.054346

### Try Pre-Trained Stage 2 Gradient Boosting

In [436]:
# Load the saved model
gb_stage2 = joblib.load("./model_weights/best_xgb_model_time_raw.pkl")

# Use the LOADED model instance to predict
pred_log = gb_stage2.predict(X_test_time)

test_mse = mean_squared_error(y_test_time, pred_log)
test_r2 = r2_score(y_test_time, pred_log)

print("\n--- Final Test Set Metrics (Original Physical Scale) ---")
print(f"MSE = {test_mse:.4f} | R² = {test_r2:.4f}")

# 4. Quantiled Relative Error Distribution (Original Scale)
relative_error = np.abs(pred_log - y_test_time) / (np.abs(y_test_time) + 1e-8)

quantiles = [0.25, 0.50, 0.75]
print("\n--- Quantiled Relative Error Q(q) (Test Set) ---")
print(f"{target_col_model}:")
print(f"Quantile (q) | Relative Error Value Q(q)")

q_values = np.quantile(relative_error, quantiles)
for q, val in zip(quantiles, q_values):
    print(f"  Q({q:.2f}):  {val:.4f}")

--- Final Test Set Metrics (Original Physical Scale) ---
MSE = 6.7783 | R² = -0.5008

--- Quantiled Relative Error Q(q) (Test Set) ---
['stats_elapsed_time']:
Quantile (q) | Relative Error Value Q(q)
  Q(0.25):  0.8476
  Q(0.50):  0.9538
  Q(0.75):  5.9993

In [408]:
evaluate_model(joblib.load("./model_weights/best_xgb_model_time_raw.pkl"))

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (MODEL)
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100            100         0.2121      0.0003         1    0.0002            1.0000    1.2667
     argtrig    100            100         0.2121      0.0092        61    0.0081            1.0000    1.1280
     arwhead   1000            100         0.2121      0.0460         3    0.0401            1.0000    1.1480
     brownal    100            100         0.2121      0.0006         1    0.0003            1.0000    1.9787
      brybnd  10000            100         0.2121     24.4133         1   23.0197            1.0605    1.0605
    clplatea    961            100         0.7492      1.1928        97    1.0576            1.1278    1.1278
    clplatec    100            100         0.2121      0.0208        87    0.0129            1.0000    1.6133
      cosine    100            100         0.2121      0.0102         1    0.0006            1.0000   16.0673
    cragglvy   1000            100         0.2121      0.3387        12    0.2475            1.0000    1.3683
    cragglvy  10000            100         0.2121     37.0681         6   24.4994            1.5130    1.5130
   cragglvy2   1000            100         0.2121      0.3275        27    0.2948            1.0000    1.1109
       curly    100            100         0.2121      0.0464        96    0.0414            1.0000    1.1222
     curly30   1000            100         0.7492    126.3817        99  124.8367            1.0124    1.0124
    dixmaanf   9999            100         0.2121    307.7376        56  305.1083            1.0086    1.0086
    dixmaang   9999            100         0.2121    301.0419        87  281.7172            1.0686    1.0686
    dixmaani     99            100         0.2121      0.0378        96    0.0352            1.0000    1.0745
    dixmaank    999            100         0.2121      2.9637       100    2.9637            1.0000    1.0000
    dixmaanl    999            100         0.2121      2.4082        66    2.2922            1.0506    1.0506
    dixmaanl   9999            100         0.2121    260.7683        32  251.7549            1.0358    1.0358
    dixmaann     99            100         0.2121      0.0559        99    0.0486            1.0000    1.1504
    dixmaann    999            100         0.2121     39.1586         1   20.1127            1.9470    1.9470
     dqdrtic   1000            100         0.2121      0.0308         9    0.0307            1.0000    1.0019
    extrosnb 100000            100         0.2121    657.8357        79  533.5132            1.2330    1.2330
fletcbv3_mod  10000            100         0.2121     97.4088         2   49.9359            1.9507    1.9507
    fletchcr   1000            100         0.7492      4.7499        36    4.0615            1.1695    1.1695
    freuroth    100            100         0.2121      0.0031        23    0.0020            1.0000    1.5366
    genhumps    100            100         0.2121      0.1849         9    0.0745            2.4802    2.4802
       ncb20    100            100         0.2121      0.0653        99    0.0598            1.0000    1.0926
      ncb20b   1000              4         0.2121    100.0779        96   26.6734            3.7520    3.7520
      nondia    100            100         0.2121      0.0007         3    0.0003            1.0000    2.1928
    penalty1  10000            100         0.2121      8.0709         2    8.0374            1.0000    1.0042
    penalty3   1000            100         0.7492      2.3161        15    2.0990            1.1034    1.1034
      quartc  10000            100         0.2121      4.4665         1    4.2661            1.0470    1.0470
     sinquad   1000             70         0.2121      1.2802        52    0.6837            1.8724    1.8724
    sparsine   1000            100         0.2121     51.3243        99   48.9996            1.0474    1.0474
    sparsqur   1000            100         0.2121      0.1433         7    0.0832            1.0000    1.7226
    srosenbr    100            100         0.2121      0.0017         4    0.0007            1.0000    2.4862
    tquartic    100            100         0.2121      0.0007         4    0.0004            1.0000    1.9622
    tquartic 100000            100         0.2121    578.0300        75  471.3734            1.2263    1.2263
      tridia   1000             84         0.4352      1.1371        70    1.0818            1.0000    1.0511
      vardim   1000            100         0.2121     31.2277         6   31.0967            1.0042    1.0042
       woods    100            100         0.2121      0.0032         6    0.0012            1.0000    2.7522
       woods  10000            100         0.2121      7.7592        12    7.3593            1.0543    1.0543
=================================================================================================================================================

==================================================
AGGREGATE METRICS (MODEL)
==================================================
0.50   1.0000
0.75   1.0860
0.90   1.8005
--------------------------------------------------
Global Mean Perf. Ratio     : 1.2038
Geometric Mean Perf. Ratio  : 1.1437
Maximum Performance Ratio   : 3.7520
--------------------------------------------------
Total Actual Compute Time   : 2650.1457s
Total Oracle Optimal Time   : 2227.5261s
==================================================

,name,nvar,predicted_mem,predicted_time,actual_time,best_mem,best_time,performance_ratio,raw_ratio
0,arglinb,100,100,0.212050,0.000290,1,0.000229,1.000000,1.266667
1,argtrig,100,100,0.212050,0.009166,61,0.008126,1.000000,1.127982
2,arwhead,1000,100,0.212050,0.045992,3,0.040062,1.000000,1.148013
3,brownal,100,100,0.212050,0.000554,1,0.000280,1.000000,1.978705
4,brybnd,10000,100,0.212050,24.413258,1,23.019709,1.060537,1.060537
5,clplatea,961,100,0.749200,1.192818,97,1.057629,1.127823,1.127823
6,clplatec,100,100,0.212050,0.020761,87,0.012869,1.000000,1.613273
7,cosine,100,100,0.212050,0.010186,1,0.000634,1.000000,16.067319
8,cragglvy,1000,100,0.212050,0.338653,12,0.247496,1.000000,1.368317
9,cragglvy,10000,100,0.212050,37.068113,6,24.499405,1.513021,1.513021
10,cragglvy2,1000,100,0.212050,0.327460,27,0.294773,1.000000,1.110888
11,curly,100,100,0.212050,0.046426,96,0.041372,1.000000,1.122154
12,curly30,1000,100,0.749200,126.381677,99,124.836701,1.012376,1.012376
13,dixmaanf,9999,100,0.212050,307.737610,56,305.108326,1.008618,1.008618
14,dixmaang,9999,100,0.212050,301.041943,87,281.717223,1.068596,1.068596
15,dixmaani,99,100,0.212050,0.037843,96,0.035220,1.000000,1.074477
16,dixmaank,999,100,0.212050,2.963739,100,2.963739,1.000000,1.000000
17,dixmaanl,999,100,0.212050,2.408196,66,2.292193,1.050608,1.050608
18,dixmaanl,9999,100,0.212050,260.768332,32,251.754948,1.035802,1.035802
19,dixmaann,99,100,0.212050,0.055941,99,0.048629,1.000000,1.150364
20,dixmaann,999,100,0.212050,39.158556,1,20.112668,1.946960,1.946960
21,dqdrtic,1000,100,0.212050,0.030756,9,0.030697,1.000000,1.001926
22,extrosnb,100000,100,0.212050,657.835676,79,533.513211,1.233026,1.233026
23,fletcbv3_mod,10000,100,0.212050,97.408820,2,49.935938,1.950676,1.950676
24,fletchcr,1000,100,0.749200,4.749922,36,4.061515,1.169495,1.169495
25,freuroth,100,100,0.212050,0.003150,23,0.002050,1.000000,1.536636
26,genhumps,100,100,0.212050,0.184860,9,0.074535,2.480181,2.480181
27,ncb20,100,100,0.212050,0.065345,99,0.059805,1.000000,1.092633
28,ncb20b,1000,4,0.212050,100.077912,96,26.673420,3.751972,3.751972
29,nondia,100,100,0.212050,0.000678,3,0.000309,1.000000,2.192753
30,penalty1,10000,100,0.212050,8.070869,2,8.037379,1.000000,1.004167
31,penalty3,1000,100,0.749200,2.316102,15,2.098970,1.103447,1.103447
32,quartc,10000,100,0.212050,4.466477,1,4.266108,1.046968,1.046968
33,sinquad,1000,70,0.212050,1.280226,52,0.683725,1.872428,1.872428
34,sparsine,1000,100,0.212050,51.324333,99,48.999589,1.047444,1.047444
35,sparsqur,1000,100,0.212050,0.143327,7,0.083205,1.000000,1.722577
36,srosenbr,100,100,0.212050,0.001713,4,0.000689,1.000000,2.486159
37,tquartic,100,100,0.212050,0.000742,4,0.000378,1.000000,1.962169
38,tquartic,100000,100,0.212050,578.029979,75,471.373380,1.226268,1.226268
39,tridia,1000,84,0.435199,1.137120,70,1.081799,1.000000,1.051138
40,vardim,1000,100,0.212050,31.227748,6,31.096726,1.004213,1.004213
41,woods,100,100,0.212050,0.003198,6,0.001162,1.000000,2.752154
42,woods,10000,100,0.212050,7.759227,12,7.359282,1.054346,1.054346

## Baseline Performance

In [262]:
import pandas as pd

print("--------------------------------------------------------------------\n"
      "Performance For Static Heuristic Baselines (Mem=5 vs. Mem=87)")

group_cols = ["name", "nvar"]

# 1. Oracle Selection (Heuristic: Min actual time, break ties with LARGEST mem)
oracle_choices = (
    test_df.sort_values(by=group_cols + ["stats_elapsed_time", "mem"], ascending=[True, True, True, False])
    .groupby(group_cols).first().reset_index()
    [group_cols + ["mem", "stats_elapsed_time"]]
    .rename(columns={"mem": "best_mem", "stats_elapsed_time": "best_time"})
)

# 2. Extract actual recorded times when mem = 5 (Baseline 1: JSOSolver default)
baseline_5 = (
    test_df[test_df["mem"] == 5][group_cols + ["stats_elapsed_time"]]
    .rename(columns={"stats_elapsed_time": "time_mem5"})
)

# 3. Extract actual recorded times when mem = 87 (Baseline 2: Global Best)
baseline_87 = (
    test_df[test_df["mem"] == 87][group_cols + ["stats_elapsed_time"]]
    .rename(columns={"stats_elapsed_time": "time_mem87"})
)

# 4. Merge baseline profiles into a unified comparison matrix
comparison_df = pd.merge(oracle_choices, baseline_5, on=group_cols, how="left")
comparison_df = pd.merge(comparison_df, baseline_87, on=group_cols, how="left")

# 5. Calculate individual performance ratios (Actual Baseline Time / True Oracle Time)
comparison_df["ratio_mem5"] = comparison_df["time_mem5"] / comparison_df["best_time"]
comparison_df["ratio_mem87"] = comparison_df["time_mem87"] / comparison_df["best_time"]

# Reorder columns for scannability
print_cols = group_cols + ["best_mem", "best_time", "time_mem5", "ratio_mem5", "time_mem87", "ratio_mem87"]
final_baseline_df = comparison_df[print_cols]

# ==============================================================================
# VISUALIZATION & OUTPUT
# ==============================================================================

# 1. Output granular per-problem table
print("\n" + "="*145)
print("PER-PROBLEM STATIC BASELINE SIDE-BY-SIDE COMPARISON")
print("="*145)
print(final_baseline_df.to_string(index=False, formatters={
    'best_time': '{:.4f}'.format,
    'time_mem5': '{:.4f}'.format,
    'ratio_mem5': '{:.4f}'.format,
    'time_mem87': '{:.4f}'.format,
    'ratio_mem87': '{:.4f}'.format
}))
print("="*145)

# 2. Compute aggregate metrics and Global Performance Ratios
quantiles = [0.25, 0.50, 0.75, 0.90]
summary_df = pd.DataFrame({
    "Quantile (q)": quantiles,
    "Baseline 1 (mem=5)": final_baseline_df["ratio_mem5"].quantile(quantiles).values,
    "Baseline 2 (mem=87)": final_baseline_df["ratio_mem87"].quantile(quantiles).values
})

total_best_time = final_baseline_df["best_time"].sum()
total_time_mem5 = final_baseline_df["time_mem5"].sum()
total_time_mem87 = final_baseline_df["time_mem87"].sum()

global_ratio_mem5 = total_time_mem5 / total_best_time
global_ratio_mem87 = total_time_mem87 / total_best_time

print("\n" + "="*70)
print("AGGREGATE BASELINE PERFORMANCE STATISTICS")
print("="*70)
print(summary_df.to_string(index=False, formatters={
    'Baseline 1 (mem=5)': '{:.4f}'.format,
    'Baseline 2 (mem=87)': '{:.4f}'.format
}))
print("-"*70)
print(f"Total Compute Time (mem=5)        : {total_time_mem5:.4f}s")
print(f"Total Compute Time (mem=87)       : {total_time_mem87:.4f}s")
print(f"Total Oracle Optimal Time         : {total_best_time:.4f}s")
print("-"*70)
print(f"GLOBAL PERFORMANCE RATIO (mem=5)  : {global_ratio_mem5:.4f}")
print(f"GLOBAL PERFORMANCE RATIO (mem=87) : {global_ratio_mem87:.4f}")
print("="*70)

--------------------------------------------------------------------
Performance For Static Heuristic Baselines (Mem=5 vs. Mem=87)

=================================================================================================================================================
PER-PROBLEM STATIC BASELINE SIDE-BY-SIDE COMPARISON
=================================================================================================================================================
        name   nvar  best_mem best_time time_mem5 ratio_mem5 time_mem87 ratio_mem87
     arglinb    100         1    0.0002    0.0002     1.0229     0.0003      1.2625
     argtrig    100        61    0.0081    0.0112     1.3724     0.0117      1.4379
     arwhead   1000         3    0.0401    0.0403     1.0068     0.0460      1.1474
     brownal    100         1    0.0003    0.0004     1.5009     0.0006      1.9761
      brybnd  10000         1   23.0197   24.3815     1.0592    24.3938      1.0597
    clplatea    961        97    1.0576    2.9448     2.7843     1.3719      1.2972
    clplatec    100        87    0.0129    0.4126    32.0606     0.0129      1.0000
      cosine    100         1    0.0006    0.0011     1.6988     0.0012      1.8879
    cragglvy   1000        12    0.2475    0.3020     1.2202     0.3392      1.3704
    cragglvy  10000         6   24.4994   40.8602     1.6678    37.1007      1.5144
   cragglvy2   1000        27    0.2948    0.3637     1.2337     0.3268      1.1086
       curly    100        96    0.0414    0.2862     6.9175     0.0548      1.3255
     curly30   1000        99  124.8367  192.1095     1.5389   126.5341      1.0136
    dixmaanf   9999        56  305.1083  314.4470     1.0306   308.1566      1.0100
    dixmaang   9999        87  281.7172  312.8415     1.1105   281.7172      1.0000
    dixmaani     99        96    0.0352    0.0483     1.3720     0.0357      1.0130
    dixmaank    999       100    2.9637    3.4064     1.1493     3.1332      1.0572
    dixmaanl    999        66    2.2922    2.6721     1.1657     2.4066      1.0499
    dixmaanl   9999        32  251.7549  286.0939     1.1364   260.5821      1.0351
    dixmaann     99        99    0.0486    0.1085     2.2306     0.0564      1.1588
    dixmaann    999         1   20.1127   39.8394     1.9808    38.5083      1.9146
     dqdrtic   1000         9    0.0307    0.0368     1.1982     0.0308      1.0017
    extrosnb 100000        79  533.5132  847.5131     1.5886   544.5883      1.0208
fletcbv3_mod  10000         2   49.9359   60.7207     1.2160    97.4184      1.9509
    fletchcr   1000        36    4.0615    6.1193     1.5067     4.4480      1.0952
    freuroth    100        23    0.0020    0.0022     1.0858     0.0021      1.0127
    genhumps    100         9    0.0745    0.0821     1.1015     0.1699      2.2801
       ncb20    100        99    0.0598    0.3278     5.4805     0.0629      1.0523
      ncb20b   1000        96   26.6734   92.3097     3.4607    27.6164      1.0354
      nondia    100         3    0.0003    0.0005     1.6076     0.0007      2.1403
    penalty1  10000         2    8.0374    8.0416     1.0005     8.0449      1.0009
    penalty3   1000        15    2.0990    2.3934     1.1403     2.4249      1.1553
      quartc  10000         1    4.2661    4.2665     1.0001     4.4658      1.0468
     sinquad   1000        52    0.6837    1.2761     1.8663     0.8536      1.2484
    sparsine   1000        99   48.9996  111.8222     2.2821    51.2389      1.0457
    sparsqur   1000         7    0.0832    0.0835     1.0039     0.1433      1.7228
    srosenbr    100         4    0.0007    0.0007     1.0651     0.0017      2.4657
    tquartic    100         4    0.0004    0.0005     1.2245     0.0008      2.0631
    tquartic 100000        75  471.3734  910.0602     1.9307   607.0365      1.2878
      tridia   1000        70    1.0818    2.0456     1.8909     1.2028      1.1118
      vardim   1000         6   31.0967   31.1121     1.0005    31.2894      1.0062
       woods    100         6    0.0012    0.0013     1.1213     0.0032      2.7460
       woods  10000        12    7.3593    9.4464     1.2836     7.7574      1.0541
=================================================================================================================================================

======================================================================
AGGREGATE BASELINE PERFORMANCE STATISTICS
======================================================================
 Quantile (q) Baseline 1 (mem=5) Baseline 2 (mem=87)
         0.25             1.1060              1.0352
         0.50             1.2337              1.1118
         0.75             1.7825              1.4761
         0.90             2.6839              2.0457
----------------------------------------------------------------------
Total Compute Time (mem=5)        : 3308.8329s
Total Compute Time (mem=87)       : 2473.5909s
Total Oracle Optimal Time         : 2227.5261s
----------------------------------------------------------------------
GLOBAL PERFORMANCE RATIO (mem=5)  : 1.4854
GLOBAL PERFORMANCE RATIO (mem=87) : 1.1105
======================================================================

In [393]:
class StaticBaselineModel:
    def __init__(self, target_mem):
        self.target_mem = target_mem
        
    def predict(self, X):
        # Force the selection logic to always pick the target memory tier
        return np.where(test_df["mem"] == self.target_mem, 0.0, 9999.0)

# ==============================================================================
# UNIFIED BASELINE EVALUATION RUNS
# ==============================================================================
evaluate_model(StaticBaselineModel(5), label="Baseline 1 (Mem=5)")
evaluate_model(StaticBaselineModel(87), label="Baseline 2 (Mem=87)")

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (BASELINE 1 (MEM=5))
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100              5         0.0000      0.0002         1    0.0002            1.0000    1.0229
     argtrig    100              5         0.0000      0.0112        61    0.0081            1.0000    1.3724
     arwhead   1000              5         0.0000      0.0403         3    0.0401            1.0000    1.0068
     brownal    100              5         0.0000      0.0004         1    0.0003            1.0000    1.5009
      brybnd  10000              5         0.0000     24.3815         1   23.0197            1.0592    1.0592
    clplatea    961              5         0.0000      2.9448        97    1.0576            2.7843    2.7843
    clplatec    100              5         0.0000      0.4126        87    0.0129           32.0606   32.0606
      cosine    100              5         0.0000      0.0011         1    0.0006            1.0000    1.6988
    cragglvy   1000              5         0.0000      0.3020        12    0.2475            1.0000    1.2202
    cragglvy  10000              5         0.0000     40.8602         6   24.4994            1.6678    1.6678
   cragglvy2   1000              5         0.0000      0.3637        27    0.2948            1.0000    1.2337
       curly    100              5         0.0000      0.2862        96    0.0414            6.9175    6.9175
     curly30   1000              5         0.0000    192.1095        99  124.8367            1.5389    1.5389
    dixmaanf   9999              5         0.0000    314.4470        56  305.1083            1.0306    1.0306
    dixmaang   9999              5         0.0000    312.8415        87  281.7172            1.1105    1.1105
    dixmaani     99              5         0.0000      0.0483        96    0.0352            1.0000    1.3720
    dixmaank    999              5         0.0000      3.4064       100    2.9637            1.1493    1.1493
    dixmaanl    999              5         0.0000      2.6721        66    2.2922            1.1657    1.1657
    dixmaanl   9999              5         0.0000    286.0939        32  251.7549            1.1364    1.1364
    dixmaann     99              5         0.0000      0.1085        99    0.0486            1.0000    2.2306
    dixmaann    999              5         0.0000     39.8394         1   20.1127            1.9808    1.9808
     dqdrtic   1000              5         0.0000      0.0368         9    0.0307            1.0000    1.1982
    extrosnb 100000              5         0.0000    847.5131        79  533.5132            1.5886    1.5886
fletcbv3_mod  10000              5         0.0000     60.7207         2   49.9359            1.2160    1.2160
    fletchcr   1000              5         0.0000      6.1193        36    4.0615            1.5067    1.5067
    freuroth    100              5         0.0000      0.0022        23    0.0020            1.0000    1.0858
    genhumps    100              5         0.0000      0.0821         9    0.0745            1.0000    1.1015
       ncb20    100              5         0.0000      0.3278        99    0.0598            5.4805    5.4805
      ncb20b   1000              5         0.0000     92.3097        96   26.6734            3.4607    3.4607
      nondia    100              5         0.0000      0.0005         3    0.0003            1.0000    1.6076
    penalty1  10000              5         0.0000      8.0416         2    8.0374            1.0000    1.0005
    penalty3   1000              5         0.0000      2.3934        15    2.0990            1.1403    1.1403
      quartc  10000              5         0.0000      4.2665         1    4.2661            1.0000    1.0001
     sinquad   1000              5         0.0000      1.2761        52    0.6837            1.8663    1.8663
    sparsine   1000              5         0.0000    111.8222        99   48.9996            2.2821    2.2821
    sparsqur   1000              5         0.0000      0.0835         7    0.0832            1.0000    1.0039
    srosenbr    100              5         0.0000      0.0007         4    0.0007            1.0000    1.0651
    tquartic    100              5         0.0000      0.0005         4    0.0004            1.0000    1.2245
    tquartic 100000              5         0.0000    910.0602        75  471.3734            1.9307    1.9307
      tridia   1000              5         0.0000      2.0456        70    1.0818            1.8909    1.8909
      vardim   1000              5         0.0000     31.1121         6   31.0967            1.0000    1.0005
       woods    100              5         0.0000      0.0013         6    0.0012            1.0000    1.1213
       woods  10000              5         0.0000      9.4464        12    7.3593            1.2836    1.2836
=================================================================================================================================================

==================================================
AGGREGATE METRICS (BASELINE 1 (MEM=5))
==================================================
0.50   1.0592
0.75   1.6282
0.90   2.6839
--------------------------------------------------
Global Mean Perf. Ratio     : 2.2616
Geometric Mean Perf. Ratio  : 1.4441
Maximum Performance Ratio   : 32.0606
--------------------------------------------------
Total Actual Compute Time   : 3308.8329s
Total Oracle Optimal Time   : 2227.5261s
==================================================

=================================================================================================================================================
PER-PROBLEM PERFORMANCE PROFILE SUMMARY (BASELINE 2 (MEM=87))
=================================================================================================================================================
        name   nvar  predicted_mem predicted_time actual_time  best_mem best_time performance_ratio raw_ratio
     arglinb    100             87         0.0000      0.0003         1    0.0002            1.0000    1.2625
     argtrig    100             87         0.0000      0.0117        61    0.0081            1.0000    1.4379
     arwhead   1000             87         0.0000      0.0460         3    0.0401            1.0000    1.1474
     brownal    100             87         0.0000      0.0006         1    0.0003            1.0000    1.9761
      brybnd  10000             87         0.0000     24.3938         1   23.0197            1.0597    1.0597
    clplatea    961             87         0.0000      1.3719        97    1.0576            1.2972    1.2972
    clplatec    100             87         0.0000      0.0129        87    0.0129            1.0000    1.0000
      cosine    100             87         0.0000      0.0012         1    0.0006            1.0000    1.8879
    cragglvy   1000             87         0.0000      0.3392        12    0.2475            1.0000    1.3704
    cragglvy  10000             87         0.0000     37.1007         6   24.4994            1.5144    1.5144
   cragglvy2   1000             87         0.0000      0.3268        27    0.2948            1.0000    1.1086
       curly    100             87         0.0000      0.0548        96    0.0414            1.0000    1.3255
     curly30   1000             87         0.0000    126.5341        99  124.8367            1.0136    1.0136
    dixmaanf   9999             87         0.0000    308.1566        56  305.1083            1.0100    1.0100
    dixmaang   9999             87         0.0000    281.7172        87  281.7172            1.0000    1.0000
    dixmaani     99             87         0.0000      0.0357        96    0.0352            1.0000    1.0130
    dixmaank    999             87         0.0000      3.1332       100    2.9637            1.0572    1.0572
    dixmaanl    999             87         0.0000      2.4066        66    2.2922            1.0499    1.0499
    dixmaanl   9999             87         0.0000    260.5821        32  251.7549            1.0351    1.0351
    dixmaann     99             87         0.0000      0.0564        99    0.0486            1.0000    1.1588
    dixmaann    999             87         0.0000     38.5083         1   20.1127            1.9146    1.9146
     dqdrtic   1000             87         0.0000      0.0308         9    0.0307            1.0000    1.0017
    extrosnb 100000             87         0.0000    544.5883        79  533.5132            1.0208    1.0208
fletcbv3_mod  10000             87         0.0000     97.4184         2   49.9359            1.9509    1.9509
    fletchcr   1000             87         0.0000      4.4480        36    4.0615            1.0952    1.0952
    freuroth    100             87         0.0000      0.0021        23    0.0020            1.0000    1.0127
    genhumps    100             87         0.0000      0.1699         9    0.0745            1.0000    2.2801
       ncb20    100             87         0.0000      0.0629        99    0.0598            1.0000    1.0523
      ncb20b   1000             87         0.0000     27.6164        96   26.6734            1.0354    1.0354
      nondia    100             87         0.0000      0.0007         3    0.0003            1.0000    2.1403
    penalty1  10000             87         0.0000      8.0449         2    8.0374            1.0000    1.0009
    penalty3   1000             87         0.0000      2.4249        15    2.0990            1.1553    1.1553
      quartc  10000             87         0.0000      4.4658         1    4.2661            1.0468    1.0468
     sinquad   1000             87         0.0000      0.8536        52    0.6837            1.2484    1.2484
    sparsine   1000             87         0.0000     51.2389        99   48.9996            1.0457    1.0457
    sparsqur   1000             87         0.0000      0.1433         7    0.0832            1.0000    1.7228
    srosenbr    100             87         0.0000      0.0017         4    0.0007            1.0000    2.4657
    tquartic    100             87         0.0000      0.0008         4    0.0004            1.0000    2.0631
    tquartic 100000             87         0.0000    607.0365        75  471.3734            1.2878    1.2878
      tridia   1000             87         0.0000      1.2028        70    1.0818            1.1118    1.1118
      vardim   1000             87         0.0000     31.2894         6   31.0967            1.0062    1.0062
       woods    100             87         0.0000      0.0032         6    0.0012            1.0000    2.7460
       woods  10000             87         0.0000      7.7574        12    7.3593            1.0541    1.0541
=================================================================================================================================================

==================================================
AGGREGATE METRICS (BASELINE 2 (MEM=87))
==================================================
0.50   1.0000
0.75   1.0556
0.90   1.2799
--------------------------------------------------
Global Mean Perf. Ratio     : 1.0933
Geometric Mean Perf. Ratio  : 1.0781
Maximum Performance Ratio   : 1.9509
--------------------------------------------------
Total Actual Compute Time   : 2473.5909s
Total Oracle Optimal Time   : 2227.5261s
==================================================

,name,nvar,predicted_mem,predicted_time,actual_time,best_mem,best_time,performance_ratio,raw_ratio
0,arglinb,100,87,0.0,0.000289,1,0.000229,1.000000,1.262500
1,argtrig,100,87,0.0,0.011684,61,0.008126,1.000000,1.437872
2,arwhead,1000,87,0.0,0.045967,3,0.040062,1.000000,1.147394
3,brownal,100,87,0.0,0.000553,1,0.000280,1.000000,1.976150
4,brybnd,10000,87,0.0,24.393811,1,23.019709,1.059692,1.059692
5,clplatea,961,87,0.0,1.371946,97,1.057629,1.297190,1.297190
6,clplatec,100,87,0.0,0.012869,87,0.012869,1.000000,1.000000
7,cosine,100,87,0.0,0.001197,1,0.000634,1.000000,1.887928
8,cragglvy,1000,87,0.0,0.339179,12,0.247496,1.000000,1.370442
9,cragglvy,10000,87,0.0,37.100730,6,24.499405,1.514352,1.514352
10,cragglvy2,1000,87,0.0,0.326788,27,0.294773,1.000000,1.108608
11,curly,100,87,0.0,0.054838,96,0.041372,1.000000,1.325482
12,curly30,1000,87,0.0,126.534108,99,124.836701,1.013597,1.013597
13,dixmaanf,9999,87,0.0,308.156589,56,305.108326,1.009991,1.009991
14,dixmaang,9999,87,0.0,281.717223,87,281.717223,1.000000,1.000000
15,dixmaani,99,87,0.0,0.035677,96,0.035220,1.000000,1.012984
16,dixmaank,999,87,0.0,3.133227,100,2.963739,1.057187,1.057187
17,dixmaanl,999,87,0.0,2.406630,66,2.292193,1.049925,1.049925
18,dixmaanl,9999,87,0.0,260.582070,32,251.754948,1.035062,1.035062
19,dixmaann,99,87,0.0,0.056353,99,0.048629,1.000000,1.158836
20,dixmaann,999,87,0.0,38.508326,1,20.112668,1.914630,1.914630
21,dqdrtic,1000,87,0.0,0.030750,9,0.030697,1.000000,1.001732
22,extrosnb,100000,87,0.0,544.588259,79,533.513211,1.020759,1.020759
23,fletcbv3_mod,10000,87,0.0,97.418439,2,49.935938,1.950868,1.950868
24,fletchcr,1000,87,0.0,4.448035,36,4.061515,1.095166,1.095166
25,freuroth,100,87,0.0,0.002076,23,0.002050,1.000000,1.012677
26,genhumps,100,87,0.0,0.169947,9,0.074535,1.000000,2.280102
27,ncb20,100,87,0.0,0.062933,99,0.059805,1.000000,1.052304
28,ncb20b,1000,87,0.0,27.616415,96,26.673420,1.035353,1.035353
29,nondia,100,87,0.0,0.000662,3,0.000309,1.000000,2.140324
30,penalty1,10000,87,0.0,8.044890,2,8.037379,1.000000,1.000935
31,penalty3,1000,87,0.0,2.424932,15,2.098970,1.155296,1.155296
32,quartc,10000,87,0.0,4.465798,1,4.266108,1.046809,1.046809
33,sinquad,1000,87,0.0,0.853595,52,0.683725,1.248448,1.248448
34,sparsine,1000,87,0.0,51.238916,99,48.999589,1.045701,1.045701
35,sparsqur,1000,87,0.0,0.143349,7,0.083205,1.000000,1.722841
36,srosenbr,100,87,0.0,0.001699,4,0.000689,1.000000,2.465744
37,tquartic,100,87,0.0,0.000780,4,0.000378,1.000000,2.063052
38,tquartic,100000,87,0.0,607.036532,75,471.373380,1.287804,1.287804
39,tridia,1000,87,0.0,1.202792,70,1.081799,1.111844,1.111844
40,vardim,1000,87,0.0,31.289441,6,31.096726,1.006197,1.006197
41,woods,100,87,0.0,0.003191,6,0.001162,1.000000,2.745999
42,woods,10000,87,0.0,7.757396,12,7.359282,1.054097,1.054097