In [1]:
import matplotlib.pyplot as plt # For plotting
import numpy as np              # Linear algebra library
import pandas as pd
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', 20)

In [2]:
df = pd.read_csv("./datasets/final.csv")
# df = df[df["stats_elapsed_time"].notna()].copy().reset_index()
df

,nvmops,objective,eval_duration_solver,extract_duration_solver,stats_elapsed_time,name,dual_feas,status,timed_bytes,timed_time,timed_gctime,nlp_warmup_time,mem,neval_grad,iter,source_solver,nvar,problem,neval_obj,timestamp_solver,error_solver,vector_type,extract_duration_problem,highest_degree (ExprTree),nln_nnzj,adbackend_hessian_backend_type,minimize,count_plus_minus,alloc_obj,jtprod_available,has_equalities,time_hprod,adbackend_jprod_residual_backend_type,adbackend_ghjvprod_backend_type,nnln,jprod_residual_available,nlvb,nlvo,nlp_type,unconstrained,adbackend_jacobian_backend_type,adbackend_jprod_backend_type,hprod_residual_available,jac_available,hess_residual_available,adbackend_gradient_backend_type,float_type,ncon,is_nls,nnzo,nlvc,tree_length,count_trigonometric_function,matrix_free,nlin,time_obj,tree_depth,is_constant (ExprTree),nnzj,alloc_hprod,adbackend_jacobian_residual_backend_type,generator,alloc_hess,hess_available,count_exponential_function,islp,count_op_function,error_problem,adbackend_hprod_residual_backend_type,equality_constrained,time_grad,source_problem,has_bounds,grad_available,clinvals_nnz,jac_residual_available,bound_constrained,jprod_available,eval_duration_problem,adbackend_hessian_residual_backend_type,nequ,adbackend_jtprod_residual_backend_type,has_inequalities,is_linear (ExprTree),linearly_constrained,adbackend_jtprod_backend_type,hprod_available,jtprod_residual_available,alloc_grad,inequality_constrained,time_hess,lin_nnzj,nnzh,timestamp_problem,adbackend_hprod_backend_type,error_type,total_alloc
0,34.0,8.624897e-10,0.392040,0.100762,0.089514,dqdrtic,0.000109,first_order,124640.0,0.089571,0.000000,0.229508,1,82.0,34.0,OptimizationProb...,1000,OptimizationProb...,100.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448
1,12.0,1.763693e-09,0.392040,0.048325,0.037171,dqdrtic,0.000478,first_order,148496.0,0.037217,0.000000,0.229508,2,17.0,12.0,OptimizationProb...,1000,OptimizationProb...,23.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448
2,15.0,4.667330e-12,0.392040,0.054916,0.043753,dqdrtic,0.000050,first_order,181760.0,0.043809,0.000000,0.229508,3,20.0,15.0,OptimizationProb...,1000,OptimizationProb...,26.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448
3,11.0,1.352652e-10,0.392040,0.044040,0.032844,dqdrtic,0.000229,first_order,212448.0,0.032927,0.000000,0.229508,4,15.0,11.0,OptimizationProb...,1000,OptimizationProb...,21.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448
4,12.0,1.724090e-10,0.392040,0.047996,0.036781,dqdrtic,0.000281,first_order,244912.0,0.036879,0.000000,0.229508,5,15.0,12.0,OptimizationProb...,1000,OptimizationProb...,21.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21797,40.0,1.855425e-10,0.068329,895.371150,895.103355,srosenbr,0.000608,first_order,314445176.0,895.370630,0.204658,29.597273,96,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 14:55...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320
21798,40.0,1.855425e-10,0.068329,834.451648,834.184401,srosenbr,0.000608,first_order,317641296.0,834.451126,0.207094,29.597273,97,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:09...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320
21799,40.0,1.855425e-10,0.068329,866.002412,865.728673,srosenbr,0.000608,first_order,320841440.0,866.001898,0.207504,29.597273,98,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:23...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320
21800,40.0,1.855425e-10,0.068329,835.319132,835.027454,srosenbr,0.000608,first_order,324041584.0,835.318577,0.224858,29.597273,99,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:37...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320
21801,40.0,1.855425e-10,0.068329,863.155858,862.897778,srosenbr,0.000608,first_order,327244024.0,863.155217,0.196050,29.597273,100,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:51...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320

In [3]:
group_cols = ["problem", "name", "nvar"]

d = df[df["stats_elapsed_time"].notna()].copy()
d = df.sort_values(group_cols + ["timed_time", "mem"], ascending=True)

best_mem_df = d.groupby(group_cols, as_index=False).head(1)
best_mem_df["mem"].value_counts()

mem
1     87
3     15
4     14
7      9
6      8
      ..
41     1
73     1
76     1
88     1
82     1
Name: count, Length: 64, dtype: int64

In [4]:
best_idx = d.groupby(group_cols)["stats_elapsed_time"].idxmin()
best_mem_map = d.loc[best_idx].set_index(group_cols)["mem"]

df = df.copy()
df["best_problem_mem"] = df.set_index(group_cols).index.map(best_mem_map)
df.to_csv("./complete_data_and_metadata.csv")

In [5]:
# unique instances: one row per (problem, nvar)
instances = df[["problem", "name", "nvar"]].drop_duplicates()

# shuffle instances
instances = instances.sample(frac=1, random_state=66).reset_index(drop=True)

n = len(instances)
n_train = int(0.8 * n)
n_valid = int(0.10 * n)

train_inst = instances.iloc[:n_train]
valid_inst = instances.iloc[n_train:n_train + n_valid]
test_inst  = instances.iloc[n_train + n_valid:]

# assign rows to splits by (problem, nvar)
train_df = df.merge(train_inst, on=["problem", "nvar"], how="inner").reset_index(drop=True)
valid_df = df.merge(valid_inst, on=["problem", "nvar"], how="inner").reset_index(drop=True)
test_df  = df.merge(test_inst,  on=["problem", "nvar"], how="inner").reset_index(drop=True)
train_df

,nvmops,objective,eval_duration_solver,extract_duration_solver,stats_elapsed_time,name_x,dual_feas,status,timed_bytes,timed_time,timed_gctime,nlp_warmup_time,mem,neval_grad,iter,source_solver,nvar,problem,neval_obj,timestamp_solver,error_solver,vector_type,extract_duration_problem,highest_degree (ExprTree),nln_nnzj,adbackend_hessian_backend_type,minimize,count_plus_minus,alloc_obj,jtprod_available,has_equalities,time_hprod,adbackend_jprod_residual_backend_type,adbackend_ghjvprod_backend_type,nnln,jprod_residual_available,nlvb,nlvo,nlp_type,unconstrained,adbackend_jacobian_backend_type,adbackend_jprod_backend_type,hprod_residual_available,jac_available,hess_residual_available,adbackend_gradient_backend_type,float_type,ncon,is_nls,nnzo,nlvc,tree_length,count_trigonometric_function,matrix_free,nlin,time_obj,tree_depth,is_constant (ExprTree),nnzj,alloc_hprod,adbackend_jacobian_residual_backend_type,generator,alloc_hess,hess_available,count_exponential_function,islp,count_op_function,error_problem,adbackend_hprod_residual_backend_type,equality_constrained,time_grad,source_problem,has_bounds,grad_available,clinvals_nnz,jac_residual_available,bound_constrained,jprod_available,eval_duration_problem,adbackend_hessian_residual_backend_type,nequ,adbackend_jtprod_residual_backend_type,has_inequalities,is_linear (ExprTree),linearly_constrained,adbackend_jtprod_backend_type,hprod_available,jtprod_residual_available,alloc_grad,inequality_constrained,time_hess,lin_nnzj,nnzh,timestamp_problem,adbackend_hprod_backend_type,error_type,total_alloc,best_problem_mem,name_y
0,34.0,8.624897e-10,0.392040,0.100762,0.089514,dqdrtic,0.000109,first_order,124640.0,0.089571,0.000000,0.229508,1,82.0,34.0,OptimizationProb...,1000,OptimizationProb...,100.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448,9,dqdrtic
1,12.0,1.763693e-09,0.392040,0.048325,0.037171,dqdrtic,0.000478,first_order,148496.0,0.037217,0.000000,0.229508,2,17.0,12.0,OptimizationProb...,1000,OptimizationProb...,23.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448,9,dqdrtic
2,15.0,4.667330e-12,0.392040,0.054916,0.043753,dqdrtic,0.000050,first_order,181760.0,0.043809,0.000000,0.229508,3,20.0,15.0,OptimizationProb...,1000,OptimizationProb...,26.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448,9,dqdrtic
3,11.0,1.352652e-10,0.392040,0.044040,0.032844,dqdrtic,0.000229,first_order,212448.0,0.032927,0.000000,0.229508,4,15.0,11.0,OptimizationProb...,1000,OptimizationProb...,21.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448,9,dqdrtic
4,12.0,1.724090e-10,0.392040,0.047996,0.036781,dqdrtic,0.000281,first_order,244912.0,0.036879,0.000000,0.229508,5,15.0,12.0,OptimizationProb...,1000,OptimizationProb...,21.0,2026-02-28 22:33...,NaN,Vector{Float64},6.848012,2.0,0.0,ADNLPModels.Empt...,True,999.0,444983408.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,1000.0,1000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,1000.0,1000.0,3992.0,0.0,True,0.0,0.930594,5.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,4991.0,NaN,ADNLPModels.Empt...,False,0.601327,OptimizationProb...,False,True,0.0,NaN,False,False,2.515710,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,2.789270e+08,False,NaN,0.0,5.005000e+05,2026-01-31 17:27...,ADNLPModels.Forw...,NaN,723.910448,9,dqdrtic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17253,40.0,1.855425e-10,0.068329,895.371150,895.103355,srosenbr,0.000608,first_order,314445176.0,895.370630,0.204658,29.597273,96,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 14:55...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320,97,srosenbr
17254,40.0,1.855425e-10,0.068329,834.451648,834.184401,srosenbr,0.000608,first_order,317641296.0,834.451126,0.207094,29.597273,97,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:09...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320,97,srosenbr
17255,40.0,1.855425e-10,0.068329,866.002412,865.728673,srosenbr,0.000608,first_order,320841440.0,866.001898,0.207504,29.597273,98,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:23...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320,97,srosenbr
17256,40.0,1.855425e-10,0.068329,835.319132,835.027454,srosenbr,0.000608,first_order,324041584.0,835.318577,0.224858,29.597273,99,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:37...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320,97,srosenbr
17257,40.0,1.855425e-10,0.068329,863.155858,862.897778,srosenbr,0.000608,first_order,327244024.0,863.155217,0.196050,29.597273,100,47.0,40.0,OptimizationProb...,100000,OptimizationProb...,54.0,2026-03-08 15:51...,NaN,Vector{Float64},3202.563014,2.0,0.0,ADNLPModels.Empt...,True,150001.0,98039312.0,False,False,NaN,ADNLPModels.Empt...,ADNLPModels.Empt...,0.0,NaN,100000.0,100000.0,ADNLPModel{Float...,True,ADNLPModels.Empt...,ADNLPModels.Empt...,NaN,False,NaN,ADNLPModels.Forw...,Float64,0.0,False,100000.0,100000.0,250000.0,0.0,True,0.0,0.066624,7.0,False,0.0,NaN,ADNLPModels.Empt...,OptimizationProb...,NaN,True,0.0,False,350001.0,NaN,ADNLPModels.Empt...,False,32.666519,OptimizationProb...,False,True,0.0,NaN,False,False,1.003211,ADNLPModels.Empt...,NaN,ADNLPModels.Empt...,False,False,False,ADNLPModels.Empt...,True,NaN,3.261877e+10,False,NaN,0.0,5.000050e+09,2026-01-28 16:05...,ADNLPModels.Forw...,NaN,32716.807320,97,srosenbr

In [6]:
instances

                 problem      name    nvar
0    OptimizationProb...  fletcbv2     100
1    OptimizationProb...       eg2     100
2    OptimizationProb...  sparsqur     100
3    OptimizationProb...  dixmaann      99
4    OptimizationProb...  dixmaanh     999
..                   ...       ...     ...
275  OptimizationProb...  dixmaanj   99999
276  OptimizationProb...  clplatec     100
277  OptimizationProb...    morebv     100
278  OptimizationProb...   arwhead     100
279  OptimizationProb...    vardim  100000

[280 rows x 3 columns]

In [7]:
from sklearn.ensemble import RandomForestRegressor
feature_cols = ["nvar", 
                "tree_length", 
                "tree_depth", 
                "time_obj", #init
                "time_grad",
                "mem",
                ]
target_col = "stats_elapsed_time" #(neval_obj, neval_grad, timed_bytes) multi-variate multiple model [y_1 y_2 y_3]^T = [b0 b1 b2 b3 b4] [1 x11 x12 ... x14]
                                                                                                                            # [1 x21 x22 ... x24]
                                                                                                                            # [...]   
                                                                                                                            # [1, x41 x42 ... x44]  

# confirm and use the three predicted feature to predict time
                                                                                                                          #  
X_train = train_df[feature_cols].to_numpy(dtype=float)
X_valid = valid_df[feature_cols].to_numpy(dtype=float)
X_test  = test_df[feature_cols].to_numpy(dtype=float)
t_test_full  = np.log1p(test_df[target_col].to_numpy(dtype=float))

t_train = np.log1p(train_df[target_col].to_numpy(dtype=float))
t_valid = np.log1p(valid_df[target_col].to_numpy(dtype=float))
t_test  = np.log1p(test_df[target_col].to_numpy(dtype=float))

In [8]:
# Generates: 1.82e+07 instead of 18248980.00
print(df[feature_cols].describe().T.to_latex(
    float_format="%.2f", 
))

\begin{tabular}{lrrrrrrrr}
\toprule
 & count & mean & std & min & 25% & 50% & 75% & max \\
\midrule
nvar & 21802.00 & 12587.35 & 29568.44 & 99.00 & 100.00 & 1000.00 & 10000.00 & 100000.00 \\
tree_length & 21802.00 & 141241.11 & 518541.68 & 200.00 & 887.00 & 6993.00 & 59988.00 & 9498605.00 \\
tree_depth & 21802.00 & 6.87 & 1.63 & 4.00 & 6.00 & 7.00 & 8.00 & 13.00 \\
time_obj & 21802.00 & 0.34 & 0.29 & 0.00 & 0.13 & 0.25 & 0.45 & 1.66 \\
time_grad & 21802.00 & 9.91 & 38.79 & 0.00 & 0.70 & 1.05 & 1.77 & 842.68 \\
mem & 21802.00 & 49.85 & 29.19 & 1.00 & 24.00 & 50.00 & 75.00 & 100.00 \\
\bottomrule
\end{tabular}

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

best_rf = None
best_score = np.inf
best_params = None

for n_estimators in range(100, 501, 10):
    rf = RandomForestRegressor(
        n_estimators=n_estimators
    )
    rf.fit(X_train, t_train)

    pred_valid = rf.predict(X_valid)
    mse_valid = mean_squared_error(t_valid, pred_valid)

    if mse_valid < best_score:
        best_score = mse_valid
        best_rf = rf
        best_params = n_estimators
        print(
                "New best:",
                "n =", n_estimators,
                "mse =", mse_valid,
            )
    else:
        print(
                "n =", n_estimators,
                "mse =", mse_valid,
            )

print("Best validation MSE (forest):", best_score)
print("Best n_estimators:", best_params)

New best: n = 100 mse = 1.1357254270875843
New best: n = 110 mse = 1.0534344959764632
New best: n = 120 mse = 1.0486251897143426
n = 130 mse = 1.0738523002673481
n = 140 mse = 1.1091461910430085
n = 150 mse = 1.0754804351546112
New best: n = 160 mse = 1.0363706176105283
n = 170 mse = 1.0942678860960873
n = 180 mse = 1.0983226392352736
n = 190 mse = 1.070767166538099
n = 200 mse = 1.0903001495806317
n = 210 mse = 1.0931252461994216
n = 220 mse = 1.1428975508574466
n = 230 mse = 1.071623595335078
n = 240 mse = 1.089126384542124
n = 250 mse = 1.0940824609258157
n = 260 mse = 1.0767249836151855
n = 270 mse = 1.069945206665382
n = 280 mse = 1.111786033826258
n = 290 mse = 1.0702655399021104
n = 300 mse = 1.089515818165566
n = 310 mse = 1.0956901552496647
n = 320 mse = 1.1000946121645339
n = 330 mse = 1.108741279732098
n = 340 mse = 1.1101303992426792
n = 350 mse = 1.0767716889080783
n = 360 mse = 1.078367508741308
n = 370 mse = 1.040039504770155
n = 380 mse = 1.0823115354218946
n = 390 mse = 1.0936979943880827
n = 400 mse = 1.0952174756475885
n = 410 mse = 1.0777703837083252
n = 420 mse = 1.1088085047198573
n = 430 mse = 1.1250147442738472
n = 440 mse = 1.0597952210404444
n = 450 mse = 1.1023539374950153
n = 460 mse = 1.0507825373140578
n = 470 mse = 1.1506500553536303
n = 480 mse = 1.0848036080426688
n = 490 mse = 1.045759662217131
n = 500 mse = 1.0743017781204045
Best validation MSE (forest): 1.0363706176105283
Best n_estimators: 160

In [10]:
feature_cols = [c for c in feature_cols if c != "mem"]
X_test  = test_df[feature_cols]
group_cols = ["problem", "nvar"]
problem_feature_cols = [c for c in feature_cols if c != "mem"]
X_test = (
    test_df.sort_values(group_cols)
           .drop_duplicates(subset=group_cols, keep="first")[problem_feature_cols]
           .reset_index(drop=True)
)
X_test

      nvar  tree_length  tree_depth  time_obj   time_grad
0      100        397.0         5.0  0.358710    0.703767
1      100       1153.0         7.0  0.239470    0.805037
2      100        642.0         7.0  0.243938    0.767900
3      100        796.0         6.0  1.121875    1.085138
4     1000       2997.0         6.0  0.081053    0.390177
5    10000      29997.0         6.0  0.082931    1.333328
6     1000       5988.0         7.0  0.433475    0.545442
7   100000    9498605.0         8.0  0.174219  221.225571
8      999       8987.0         6.0  0.000207    0.028250
9    99999     899987.0         6.0  0.021420  427.261382
10    9999      89987.0         6.0  0.170099    5.482113
11     999       8987.0         6.0  0.000368    0.068973
12   99999     899987.0         6.0  0.103955  767.584008
13      99        887.0         6.0  0.240750    1.205763
14    1000       2000.0         4.0  0.218897    1.393829
15    1000       4997.0         9.0  0.474234    1.255757
16   10000      20001.0         8.0  0.123363    0.924792
17     100        594.0         7.0  0.853712    0.757948
18     100        701.0         9.0  0.158053    0.542207
19     100        700.0         6.0  0.444468    0.589612
20   10000      20001.0         8.0  0.082842    1.170312
21   10000      30000.0         6.0  0.110180    0.885013
22  100000     300000.0         6.0  0.073975   39.079127
23     100        200.0         4.0  0.613438    0.755414
24    1000       2000.0         4.0  0.385739    0.718821
25   10000     359910.0         9.0  0.284124    5.976865
26    1000       6990.0         8.0  0.571396    0.609562
27  100000     799998.0         6.0  0.144176   73.058456

In [11]:
import math

def choose_best_mem(model, x_problem, mem_candidates):
    preds = []
    for mem in mem_candidates:
        x = np.concatenate([x_problem, [mem]])
        preds.append((mem, math.exp(model.predict(x.reshape(1, -1))[0])))
    return min(preds, key=lambda x: x[1])

In [12]:
best_n_estimators = best_params

X_train_full = np.vstack([X_train, X_valid])
t_train_full = np.concatenate([t_train, t_valid])

final_rf = RandomForestRegressor(
    n_estimators=best_n_estimators,
    random_state=66
)
X_train_full

array([[1.00000000e+03, 3.99200000e+03, 5.00000000e+00, 9.30593751e-01,
        6.01327335e-01, 1.00000000e+00],
       [1.00000000e+03, 3.99200000e+03, 5.00000000e+00, 9.30593751e-01,
        6.01327335e-01, 2.00000000e+00],
       [1.00000000e+03, 3.99200000e+03, 5.00000000e+00, 9.30593751e-01,
        6.01327335e-01, 3.00000000e+00],
       ...,
       [9.99000000e+02, 8.98700000e+03, 6.00000000e+00, 5.90842000e-04,
        9.13603980e-02, 9.80000000e+01],
       [9.99000000e+02, 8.98700000e+03, 6.00000000e+00, 5.90842000e-04,
        9.13603980e-02, 9.90000000e+01],
       [9.99000000e+02, 8.98700000e+03, 6.00000000e+00, 5.90842000e-04,
        9.13603980e-02, 1.00000000e+02]], shape=(19482, 6))

In [13]:
final_rf.fit(X_train_full, t_train_full)

RandomForestRegressor(n_estimators=160, random_state=66)

In [14]:
group_cols = ["problem", "nvar"]
problem_cols = ["problem", "nvar", "mem", "best_problem_mem", "stats_elapsed_time"]

problems = (
    test_df.loc[test_df["mem"] == test_df["best_problem_mem"], problem_cols]
           .drop_duplicates(subset=group_cols, keep="first")
           .reset_index(drop=True)
           .rename(columns={"time": "best_time"})
)
problems

                problem    nvar  mem  best_problem_mem  stats_elapsed_time
0   OptimizationProb...    1000   75                75            1.000121
1   OptimizationProb...  100000    1                 1         3600.000000
2   OptimizationProb...   10000    1                 1            4.633909
3   OptimizationProb...   10000    5                 5            0.519168
4   OptimizationProb...     100    3                 3            0.009866
5   OptimizationProb...     100  100               100            0.111904
6   OptimizationProb...     100   49                49            0.002201
7   OptimizationProb...     100   71                71            0.007313
8   OptimizationProb...    1000    7                 7            0.083205
9   OptimizationProb...  100000    1                 1         3600.000000
10  OptimizationProb...     100    4                 4            0.000403
11  OptimizationProb...     100   87                87            0.012869
12  OptimizationProb...      99  100               100            0.044703
13  OptimizationProb...     999    1                 1            4.496032
14  OptimizationProb...   99999    1                 1         3600.000000
15  OptimizationProb...    1000    1                 1            0.043548
16  OptimizationProb...    9999   32                32          251.754948
17  OptimizationProb...   10000   28                28            6.227193
18  OptimizationProb...   10000    1                 1         3600.000000
19  OptimizationProb...   10000    8                 8            3.032034
20  OptimizationProb...   99999    1                 1         3600.000000
21  OptimizationProb...  100000   38                38         1092.520843
22  OptimizationProb...     100    1                 1            0.000572
23  OptimizationProb...     100   99                99            0.015649
24  OptimizationProb...    1000    1                 1            0.049867
25  OptimizationProb...    1000   12                12            0.247496
26  OptimizationProb...     999    1                 1           20.112668
27  OptimizationProb...    1000    1                 1            0.043572

In [15]:
mem_candidates = np.arange(1, 101)
preds = []

for i, x_problem in enumerate(X_test.itertuples(index=False, name=None)):
    pred = choose_best_mem(final_rf, x_problem, mem_candidates)
    preds.append(pred)

    prob_name = problems.iloc[i]["problem"]
    nvar = problems.iloc[i]["nvar"]
    actual_best_mem = problems.iloc[i]["best_problem_mem"]

    print(
        f"Best predicted mem for {prob_name}({nvar}) is mem={pred[0]} "
        f"and the actual best mem is {actual_best_mem} with runtime={pred[1]}"
    )
preds

Best predicted mem for OptimizationProblems.ADNLPProblems.errinros_mod(; matrix_free = true, n = 1000, type = Float64)(1000) is mem=7 and the actual best mem is 75 with runtime=1.001005908683217
Best predicted mem for OptimizationProblems.ADNLPProblems.vardim(; matrix_free = true, n = 100000, type = Float64)(100000) is mem=6 and the actual best mem is 1 with runtime=1.00803929339203
Best predicted mem for OptimizationProblems.ADNLPProblems.cosine(; matrix_free = true, n = 10000, type = Float64)(10000) is mem=11 and the actual best mem is 1 with runtime=1.006104038270398
Best predicted mem for OptimizationProblems.ADNLPProblems.nondia(; matrix_free = true, n = 10000, type = Float64)(10000) is mem=5 and the actual best mem is 5 with runtime=1.0014820609446238
Best predicted mem for OptimizationProblems.ADNLPProblems.chainwoo(; matrix_free = true, n = 100, type = Float64)(100) is mem=61 and the actual best mem is 3 with runtime=1.0623044993484256
Best predicted mem for OptimizationProblems.ADNLPProblems.morebv(; matrix_free = true, n = 100, type = Float64)(100) is mem=75 and the actual best mem is 100 with runtime=21.034844996092467
Best predicted mem for OptimizationProblems.ADNLPProblems.bdqrtic(; matrix_free = true, n = 100, type = Float64)(100) is mem=25 and the actual best mem is 49 with runtime=27.3064556012069
Best predicted mem for OptimizationProblems.ADNLPProblems.indef_mod(; matrix_free = true, n = 100, type = Float64)(100) is mem=8 and the actual best mem is 71 with runtime=2497.8087466375923
Best predicted mem for OptimizationProblems.ADNLPProblems.sparsqur(; matrix_free = true, n = 1000, type = Float64)(1000) is mem=66 and the actual best mem is 7 with runtime=2.802566821637764
Best predicted mem for OptimizationProblems.ADNLPProblems.curly30(; matrix_free = true, n = 100000, type = Float64)(100000) is mem=83 and the actual best mem is 1 with runtime=1549.8105730651625

Best predicted mem for OptimizationProblems.ADNLPProblems.arwhead(; matrix_free = true, n = 100, type = Float64)(100) is mem=6 and the actual best mem is 4 with runtime=533.7238573413322
Best predicted mem for OptimizationProblems.ADNLPProblems.clplatec(; matrix_free = true, n = 100, type = Float64)(100) is mem=66 and the actual best mem is 87 with runtime=2.834598741590709
Best predicted mem for OptimizationProblems.ADNLPProblems.dixmaanp(; matrix_free = true, n = 100, type = Float64)(99) is mem=8 and the actual best mem is 100 with runtime=2658.365735384856
Best predicted mem for OptimizationProblems.ADNLPProblems.dixmaanj(; matrix_free = true, n = 1000, type = Float64)(999) is mem=37 and the actual best mem is 1 with runtime=1.0069307052873324
Best predicted mem for OptimizationProblems.ADNLPProblems.dixmaano(; matrix_free = true, n = 100000, type = Float64)(99999) is mem=5 and the actual best mem is 1 with runtime=1.033439797039732
Best predicted mem for OptimizationProblems.ADNLPProblems.dqrtic(; matrix_free = true, n = 1000, type = Float64)(1000) is mem=100 and the actual best mem is 1 with runtime=21.826566791670626
Best predicted mem for OptimizationProblems.ADNLPProblems.dixmaanl(; matrix_free = true, n = 10000, type = Float64)(9999) is mem=22 and the actual best mem is 32 with runtime=7.08983009593135
Best predicted mem for OptimizationProblems.ADNLPProblems.powellsg(; matrix_free = true, n = 10000, type = Float64)(10000) is mem=27 and the actual best mem is 28 with runtime=1.0070543718216227
Best predicted mem for OptimizationProblems.ADNLPProblems.sbrybnd(; matrix_free = true, n = 10000, type = Float64)(10000) is mem=99 and the actual best mem is 1 with runtime=1.0319614709267415
Best predicted mem for OptimizationProblems.ADNLPProblems.extrosnb(; matrix_free = true, n = 10000, type = Float64)(10000) is mem=9 and the actual best mem is 8 with runtime=1.0671453229448307
Best predicted mem for OptimizationProblems.ADNLPProblems.dixmaanj(; matrix_free = true, n = 100000, type = Float64)(99999) is mem=84 and the actual best mem is 1 with runtime=5.502267799033982
Best predicted mem for OptimizationProblems.ADNLPProblems.powellsg(; matrix_free = true, n = 100000, type = Float64)(100000) is mem=33 and the actual best mem is 38 with runtime=21.717620363936177
Best predicted mem for OptimizationProblems.ADNLPProblems.quartc(; matrix_free = true, n = 100, type = Float64)(100) is mem=100 and the actual best mem is 1 with runtime=1242.5221040845793
Best predicted mem for OptimizationProblems.ADNLPProblems.noncvxu2(; matrix_free = true, n = 100, type = Float64)(100) is mem=7 and the actual best mem is 99 with runtime=1.0006205807947348
Best predicted mem for OptimizationProblems.ADNLPProblems.cosine(; matrix_free = true, n = 1000, type = Float64)(1000) is mem=3 and the actual best mem is 1 with runtime=1.0485545679878003
Best predicted mem for OptimizationProblems.ADNLPProblems.cragglvy(; matrix_free = true, n = 1000, type = Float64)(1000) is mem=100 and the actual best mem is 12 with runtime=404.9366014416381
Best predicted mem for OptimizationProblems.ADNLPProblems.dixmaann(; matrix_free = true, n = 1000, type = Float64)(999) is mem=72 and the actual best mem is 1 with runtime=20.501782795276917
Best predicted mem for OptimizationProblems.ADNLPProblems.quartc(; matrix_free = true, n = 1000, type = Float64)(1000) is mem=9 and the actual best mem is 1 with runtime=2948.6172749129255

[(np.int64(7), 1.001005908683217),
 (np.int64(6), 1.00803929339203),
 (np.int64(11), 1.006104038270398),
 (np.int64(5), 1.0014820609446238),
 (np.int64(61), 1.0623044993484256),
 (np.int64(75), 21.034844996092467),
 (np.int64(25), 27.3064556012069),
 (np.int64(8), 2497.8087466375923),
 (np.int64(66), 2.802566821637764),
 (np.int64(83), 1549.8105730651625),
 (np.int64(6), 533.7238573413322),
 (np.int64(66), 2.834598741590709),
 (np.int64(8), 2658.365735384856),
 (np.int64(37), 1.0069307052873324),
 (np.int64(5), 1.033439797039732),
 (np.int64(100), 21.826566791670626),
 (np.int64(22), 7.08983009593135),
 (np.int64(27), 1.0070543718216227),
 (np.int64(99), 1.0319614709267415),
 (np.int64(9), 1.0671453229448307),
 (np.int64(84), 5.502267799033982),
 (np.int64(33), 21.717620363936177),
 (np.int64(100), 1242.5221040845793),
 (np.int64(7), 1.0006205807947348),
 (np.int64(3), 1.0485545679878003),
 (np.int64(100), 404.9366014416381),
 (np.int64(72), 20.501782795276917),
 (np.int64(9), 2948.6172749129255)]

In [16]:
problems["predicted_mem"] = [pred[0] for pred in preds]
problems

,problem,nvar,mem,best_problem_mem,stats_elapsed_time,predicted_mem
0,OptimizationProb...,1000,75,75,1.000121,7
1,OptimizationProb...,100000,1,1,3600.000000,6
2,OptimizationProb...,10000,1,1,4.633909,11
3,OptimizationProb...,10000,5,5,0.519168,5
4,OptimizationProb...,100,3,3,0.009866,61
5,OptimizationProb...,100,100,100,0.111904,75
6,OptimizationProb...,100,49,49,0.002201,25
7,OptimizationProb...,100,71,71,0.007313,8
8,OptimizationProb...,1000,7,7,0.083205,66
9,OptimizationProb...,100000,1,1,3600.000000,83
10,OptimizationProb...,100,4,4,0.000403,6
11,OptimizationProb...,100,87,87,0.012869,66
12,OptimizationProb...,99,100,100,0.044703,8
13,OptimizationProb...,999,1,1,4.496032,37
14,OptimizationProb...,99999,1,1,3600.000000,5
15,OptimizationProb...,1000,1,1,0.043548,100
16,OptimizationProb...,9999,32,32,251.754948,22
17,OptimizationProb...,10000,28,28,6.227193,27
18,OptimizationProb...,10000,1,1,3600.000000,99
19,OptimizationProb...,10000,8,8,3.032034,9
20,OptimizationProb...,99999,1,1,3600.000000,84
21,OptimizationProb...,100000,38,38,1092.520843,33
22,OptimizationProb...,100,1,1,0.000572,100
23,OptimizationProb...,100,99,99,0.015649,7
24,OptimizationProb...,1000,1,1,0.049867,3
25,OptimizationProb...,1000,12,12,0.247496,100
26,OptimizationProb...,999,1,1,20.112668,72
27,OptimizationProb...,1000,1,1,0.043572,9

In [17]:
feature_cols = ["nvar", 
                "expr_length", 
                "expr_depth", 
                "init_eval_obj_time", 
                "init_eval_grad_time",
                "mem",
                ]
feature_cols

['nvar',
 'expr_length',
 'expr_depth',
 'init_eval_obj_time',
 'init_eval_grad_time',
 'mem']

In [18]:
preds
actual_best_mem = problems["best_problem_mem"]
actual_best_mem

0      75
1       1
2       1
3       5
4       3
5     100
6      49
7      71
8       7
9       1
10      4
11     87
12    100
13      1
14      1
15      1
16     32
17     28
18      1
19      8
20      1
21     38
22      1
23     99
24      1
25     12
26      1
27      1
Name: best_problem_mem, dtype: int64

In [19]:
problems

,problem,nvar,mem,best_problem_mem,stats_elapsed_time,predicted_mem
0,OptimizationProb...,1000,75,75,1.000121,7
1,OptimizationProb...,100000,1,1,3600.000000,6
2,OptimizationProb...,10000,1,1,4.633909,11
3,OptimizationProb...,10000,5,5,0.519168,5
4,OptimizationProb...,100,3,3,0.009866,61
5,OptimizationProb...,100,100,100,0.111904,75
6,OptimizationProb...,100,49,49,0.002201,25
7,OptimizationProb...,100,71,71,0.007313,8
8,OptimizationProb...,1000,7,7,0.083205,66
9,OptimizationProb...,100000,1,1,3600.000000,83
10,OptimizationProb...,100,4,4,0.000403,6
11,OptimizationProb...,100,87,87,0.012869,66
12,OptimizationProb...,99,100,100,0.044703,8
13,OptimizationProb...,999,1,1,4.496032,37
14,OptimizationProb...,99999,1,1,3600.000000,5
15,OptimizationProb...,1000,1,1,0.043548,100
16,OptimizationProb...,9999,32,32,251.754948,22
17,OptimizationProb...,10000,28,28,6.227193,27
18,OptimizationProb...,10000,1,1,3600.000000,99
19,OptimizationProb...,10000,8,8,3.032034,9
20,OptimizationProb...,99999,1,1,3600.000000,84
21,OptimizationProb...,100000,38,38,1092.520843,33
22,OptimizationProb...,100,1,1,0.000572,100
23,OptimizationProb...,100,99,99,0.015649,7
24,OptimizationProb...,1000,1,1,0.049867,3
25,OptimizationProb...,1000,12,12,0.247496,100
26,OptimizationProb...,999,1,1,20.112668,72
27,OptimizationProb...,1000,1,1,0.043572,9

In [20]:
# Filter for memory 5 first
mem_5_df = df[df["mem"] == 5]

# Merge with problems to filter for the exact problem+nvar pairs
baseline_df = pd.merge(mem_5_df, problems[["problem", "nvar"]], on=["problem", "nvar"], how="inner")
baseline_df
problems["baseline_time"] = baseline_df["time"]
problems

KeyError: 'time'

In [ ]:
# 1. Clean up 'problems' to remove any old merge artifacts
cols_to_drop = [c for c in ['mem', 'mem_x', 'mem_y', 'time_x', 'time_y', 'predicted_mem_time'] if c in problems.columns]
problems = problems.drop(columns=cols_to_drop)

# 2. Prepare the lookup slice from the original data
# We use drop_duplicates to ensure a 1-to-1 mapping
lookup = df[["problem", "nvar", "mem", "time"]].drop_duplicates(subset=["problem", "nvar", "mem"])
lookup

# 3. Perform the merge
problems = pd.merge(
    problems, 
    lookup, 
    left_on=["problem", "nvar", "predicted_mem"], 
    right_on=["problem", "nvar", "mem"], 
    how="left"
)

# 4. Final Cleanup: Rename 'time' and drop the redundant 'mem'
problems = problems.rename(columns={"time": "predicted_mem_time"}).drop(columns=["mem"])
problems

,problem,nvar,best_problem_mem,best_time,predicted_mem,predicted_mem_time
0,arglinb,100,1,1.422291,30,1.422308
1,bdqrtic,100,28,1.401975,96,1.402088
2,broyden3d,100,10,1.377813,98,1.377941
3,chainwoo,100,3,1.372517,15,1.394729
4,curly,100,96,1.417469,98,1.418025
5,dixmaanh,99,19,0.015107,49,0.015659
6,dixmaanm,99,97,1.208349,98,1.212405
7,dixmaano,99,92,0.053089,6,0.082368
8,edensch,100,7,1.243068,87,1.243136
9,eg2,100,3,1.249519,63,1.249549
10,extrosnb,100,1,1.267135,100,1.267289
11,gauss2,8,95,0.687109,100,0.687246
12,indef_mod,100,38,1.292279,7,1.295700
13,lanczos1,6,16,0.372617,54,0.372745
14,palmer1c,8,68,0.558476,7,0.629658
15,palmer1d,7,91,0.460858,91,0.460858
16,palmer5c,6,15,0.399134,98,0.399181
17,schmvett,100,20,1.305534,29,1.305570
18,clplateb,961,70,2.247503,21,2.769426
19,cragglvy,1000,12,1.534018,99,1.621649
20,dqdrtic,1000,7,1.323025,47,1.323502
21,eg2,1000,11,1.277196,89,1.277337
22,fletcbv3_mod,1000,3,1.752122,100,2.392151
23,ncb20,1000,92,8.599921,87,9.481126
24,noncvxun,1000,25,10.475726,78,61.523697
25,penalty2,1000,34,301.284815,98,301.299728
26,spmsrtls,1000,98,2.636146,91,2.714563
27,tointgss,1000,72,1.338100,100,1.338424
28,tquartic,1000,5,1.368051,36,1.370625

In [ ]:
# 1. Calculate Relative Gaps (as percentages)
problems['gap_default'] = (problems['baseline_time'] - problems['best_time']) / problems['best_time']
problems['gap_model'] = (problems['predicted_mem_time'] - problems['best_time']) / problems['best_time']

# 2. Square the gaps to penalize "bad" choices more heavily
# This is like calculating a 'Variance of Suboptimality'
baseline_mean = np.mean(problems['gap_default'])
predicted_mean = np.mean(problems['gap_model'])

# 3. Improvement in "Reliability"
reliability_improvement = (1 - (predicted_mean / baseline_mean)) * 100
print(f"Our Predicted mem is {reliability_improvement:.2f}% better than the default mem=5")

Our Predicted mem is 25.36% better than the default mem=5

In [ ]:
test_mse = mean_squared_error(problems["best_time"], problems["predicted_mem_time"])
test_mae = mean_absolute_error(problems["best_time"], problems["predicted_mem_time"])
test_r2  = r2_score(problems["best_time"], problems["predicted_mem_time"])

print("Tree Test MSE (time):", test_mse)
print("Tree Test MAE (time):", test_mae)
print("Tree Test R^2 (time):", test_r2)

Tree Test MSE (time): 89.90945975528345
Tree Test MAE (time): 1.8416455788965518
Tree Test R^2 (time): 0.9699453531546912

In [ ]:
predicted_mem = np.array([pred[0] for pred in preds], dtype=int)
actual_best_mem = np.array(actual_best_mem, dtype=int)
acc = np.mean(predicted_mem == actual_best_mem)
print(f"Mem exact match accuracy: {acc:.2f}")

Mem exact match accuracy: 0.00

In [ ]:
predicted_time = problems["predicted_mem_time"]
best_time = problems["best_time"]
ratios = predicted_time / best_time
within_5  = np.mean(ratios <= 1.05)
within_10 = np.mean(ratios <= 1.10)
print(f"Median time ratio: {np.median(ratios):.2f}")
print(f"Within 5% of optimal: {within_5:.2f}")
print(f"Within 10% of optimal: {within_10:.2f}")

Median time ratio: 1.00
Within 5% of optimal: 0.76
Within 10% of optimal: 0.79

In [ ]:
rf_tree0 = final_rf.estimators_[0]
from sklearn import tree

plt.figure(figsize=(18, 10))
tree.plot_tree(
    rf_tree0,
    feature_names=feature_cols,
    filled=True,
    rounded=True,
    max_depth=3,
    fontsize=8,
    precision=6,
)
plt.title("Random Forest: tree 0 (top 3 levels)")
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.tree import export_graphviz
import os

dot_data = export_graphviz(
    rf_tree0,
    max_depth=6,
    out_file=None,               # return string instead of writing directly to file
    feature_names=feature_cols,
    filled=True,
    rounded=True,
    precision=6                  # <-- more decimal places
)

In [ ]:
from graphviz import Source

os.makedirs("../tree_plots", exist_ok=True)

tree_graph = Source(dot_data)
pdf_path = tree_graph.render(
    filename="random_forest",    # base name
    directory="../tree_plots",
    format="pdf",
    cleanup=True                     # delete intermediate .dot
)
print("PDF written to:", pdf_path)
tree_graph

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

rf_importances = final_rf.feature_importances_
indices_rf = np.argsort(rf_importances)[::-1]  

plt.figure(figsize=(10, 5))
plt.bar(range(len(feature_cols)), rf_importances[indices_rf])
plt.xticks(range(len(feature_cols)), [feature_cols[i] for i in indices_rf], rotation=45, ha="right")
plt.ylabel("Feature importance")
plt.title("Random forest feature importances")
plt.tight_layout()
plt.show()